#!/usr/bin/env bash
# tests/engine.sh — fixture-based regression harness for the true-up engine.
#
# Tests ARE the harness. This builds a SYNTHETIC target repo from scratch and runs the
# real CLI against it via --repo, proving true-up is repo-agnostic (config-driven, not
# wired to its own directory) and pinning every load-bearing invariant + incident guard.
# Fast (<60s). Run: bash tests/engine.sh   (or: npm test)
set -uo pipefail

# HERMETIC ISOLATION (load-bearing safety): this suite runs the REAL `true-up hooks --install`, which
# resolves its target via `git rev-parse --git-path hooks` and therefore HONORS `core.hooksPath`. On a
# machine with a GLOBAL core.hooksPath set, an unisolated run would overwrite the developer's real
# global git hooks (pre-commit/pre-push) — and `hooks --uninstall` would leave them removed. That
# incident is why this block exists: neutralize global/system git config (so hooksDir resolves to each
# throwaway repo's own .git/hooks) and point HOME at a throwaway so nothing reads the dev's real config.
# NEVER remove this — T32b asserts hooks land INSIDE the test repo, which only holds under isolation.
export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null GIT_CONFIG_NOSYSTEM=1
export HOME="$(mktemp -d)"

HERE="$(cd "$(dirname "$0")/.." && pwd)"
TU="node ${HERE}/bin/true-up"
pass=0 ; fail=0 ; skip=0
ok(){ printf '  \033[32mPASS\033[0m %s\n' "$1"; pass=$((pass + 1)); }
no(){ printf '  \033[31mFAIL\033[0m %s\n' "$1"; fail=$((fail + 1)); }
sk(){ printf '  \033[33mSKIP\033[0m %s\n' "$1"; skip=$((skip + 1)); }
# Optional Tier-2 deps (tree-sitter). Absent on a bare clone → Tier-2 tests SKIP (honest), never FAIL.
# Dir check (NOT `require.resolve` — web-tree-sitter is ESM-only, so require.resolve throws even when present).
HAS_TS=0; { [ -d "$HERE/node_modules/web-tree-sitter" ] && [ -d "$HERE/node_modules/tree-sitter-wasms" ]; } && HAS_TS=1

FIX="$(mktemp -d)"; H=""; C=""; P=""; E=""; V=""; M=""; S=""; Y=""; Z=""; G=""; K=""; SD=""
trap 'rm -rf "$FIX" "$H" "$C" "$P" "$E" "$V" "$M" "$S" "$Y" "$Z" "$G" "$K" "$SD"' EXIT

# --- synthesize a target repo: steward data + a generated view + an anchored doc + a symlink ---
git -C "$FIX" init -q
cat > "$FIX/.true-up.json" <<'JSON'
{
  "facts": { "data.json": [["items", "id"]] },
  "zones": [
    { "path": "secret/", "visibility": "private", "audience": "team", "intent": "encrypted-notes", "rules": ["must-be-ciphertext"] },
    { "path": "", "visibility": "public", "audience": "world", "intent": "public-default", "rules": ["no-machine-local-paths"] }
  ],
  "seed": [ { "from": "doc.md", "to": "data.json", "kind": "derives-facts-from" } ]
}
JSON
printf '%s\n' '{ "items": [ { "id": "a", "v": 1 }, { "id": "b", "v": 2 } ] }' > "$FIX/data.json"
printf '%s\n' '# generated view' '<!-- generated by build.mjs from data.json -->' 'a=1 b=2' > "$FIX/gen.md"
printf '%s\n' '# doc' 'item a has value 1.' '<!-- fact: data.json#items.a -->' > "$FIX/doc.md"
ln -s doc.md "$FIX/link.md"
git -C "$FIX" add -A && git -C "$FIX" -c user.email=t@t -c user.name=t commit -qm init

# T1 — engine runs on a FOREIGN repo via --repo, writes into the target
$TU --repo "$FIX" >/dev/null 2>&1 && ok "build runs on a foreign repo (--repo)" || no "build runs on a foreign repo"
[ -f "$FIX/.true-up/depgraph.json" ] && ok "writes .true-up/depgraph.json into the target" || no "writes depgraph.json into target"
$TU --repo "$FIX" --check >/dev/null 2>&1 && ok "--check passes when in sync" || no "--check passes when in sync"

# T2 — config-driven fact nodes + anchored edge resolve (repo-agnostic)
$TU --repo "$FIX" --impact 'data.json#items.a' 2>/dev/null | grep -q 'doc.md' && ok "anchored fact-edge resolves (doc.md <- data.json#items.a)" || no "anchored fact-edge resolves"

# T3/T4 — structural edges from conventions
grep -q 'generated-from' "$FIX/.true-up/depgraph.json" && ok "generated-from edge from self-describing marker" || no "generated-from edge"
grep -q 'alias-of' "$FIX/.true-up/depgraph.json" && ok "symlink alias-of edge (link.md -> doc.md)" || no "symlink alias-of edge"

# T5 — fail-loud on an unresolved fact-anchor
printf '%s\n' '<!-- fact: data.json#items.NOPE -->' > "$FIX/bad.md"
$TU --repo "$FIX" >/dev/null 2>&1 && no "build must FAIL on unresolved anchor" || ok "fail-loud on unresolved anchor"
rm -f "$FIX/bad.md"; $TU --repo "$FIX" >/dev/null 2>&1

# T5b — INCIDENT: anchor/marker EXAMPLES in code formatting (a doc explaining true-up's syntax)
# must NOT be parsed as live anchors (else any repo documenting true-up would fail-loud).
printf '%s\n' '# how-to' 'Anchor inline like `<!-- fact: example.json#x.y -->`, or fenced:' '```' '<!-- fact: another.json#z.w -->' '```' > "$FIX/howto.md"
$TU --repo "$FIX" >/dev/null 2>&1 && ok "anchor examples in code formatting do not fail-loud" || no "anchor examples in code must not fail-loud"
rm -f "$FIX/howto.md"; $TU --repo "$FIX" >/dev/null 2>&1

# T6 — externality detection (machine-local leak). NB: --externalities now GATES (exit 1 on a leak),
# so assert on captured OUTPUT, not the pipeline exit (pipefail would otherwise mask the grep).
printf '%s\n' 'path: /home/someuser/x' > "$FIX/leak.md"
out="$($TU --repo "$FIX" --externalities 2>/dev/null)"; echo "$out" | grep -q '\[high\]' && ok "--externalities flags a /home leak" || no "--externalities flags a leak"
rm -f "$FIX/leak.md"
out="$($TU --repo "$FIX" --externalities 2>/dev/null)"; echo "$out" | grep -q ': 0 (0 high)' && ok "--externalities clean otherwise" || no "--externalities clean otherwise"

# T7 — zone/policy gate clean
$TU --repo "$FIX" --policy 2>/dev/null | grep -q 'policy violations: 0' && ok "--policy reports 0 violations" || no "--policy reports 0 violations"

# T8 — the deterministic true-up loop reaches GREEN on a clean target
$TU --repo "$FIX" run --since HEAD 2>/dev/null | grep -q 'GREEN' && ok "run --since reaches GREEN on a clean repo" || no "run reaches GREEN"

# T9 — HIGH-1: --policy / --externalities are GATES (exit nonzero on violations), with --report opt-out
printf '%s\n' 'see /home/bob/secret/x' > "$FIX/leak2.md"
$TU --repo "$FIX" --policy >/dev/null 2>&1; rc=$?;        [ "$rc" -ne 0 ] && ok "HIGH-1: --policy EXITS NONZERO on a violation" || no "HIGH-1: --policy must gate"
$TU --repo "$FIX" --externalities >/dev/null 2>&1; rc=$?; [ "$rc" -ne 0 ] && ok "HIGH-1: --externalities EXITS NONZERO on a leak" || no "HIGH-1: --externalities must gate"
$TU --repo "$FIX" --policy --report >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "HIGH-1: --policy --report stays exit 0 (report-only)" || no "HIGH-1: --report must exit 0"
rm -f "$FIX/leak2.md"; $TU --repo "$FIX" >/dev/null 2>&1
$TU --repo "$FIX" --policy >/dev/null 2>&1; rc=$?;        [ "$rc" -eq 0 ] && ok "HIGH-1: --policy exits 0 when clean" || no "--policy must exit 0 when clean"

# T10 — HIGH-2: a machine-local path shown inside CODE formatting (docs explaining a rule) is NOT a leak
printf '%s\n' '# privacy policy' 'We reject paths like `/home/alice/private/` in values.' '```' 'example: /home/bob/scratch/' '```' > "$FIX/privacy.md"
$TU --repo "$FIX" --externalities >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "HIGH-2: /home in inline+fenced code is not flagged (stripCode in detectors)" || no "HIGH-2: code-span paths must not be flagged"
rm -f "$FIX/privacy.md"; $TU --repo "$FIX" >/dev/null 2>&1

# T11 — suppression directives mute a legit path-example in prose; scope is per-line
printf '%s\n' '# notes' 'avoid /home/eve/x/ here <!-- true-up:ignore-line -->' '<!-- true-up:ignore-next no-machine-local-paths -->' 'and /home/eve/y/ here' > "$FIX/sup.md"
$TU --repo "$FIX" --externalities >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "suppression: ignore-line + ignore-next mute path findings" || no "suppression directives must mute findings"
printf '%s\n' '# notes' 'and /home/eve/z/ here (no directive)' > "$FIX/sup.md"
$TU --repo "$FIX" --externalities >/dev/null 2>&1; rc=$?; [ "$rc" -ne 0 ] && ok "suppression is per-line (an unmarked leak still flags)" || no "unmarked leak must still flag"
rm -f "$FIX/sup.md"; $TU --repo "$FIX" >/dev/null 2>&1

# T12 — MED: --impact --since <bad ref> is exit 2, NOT a silent "0 dependents" exit 0
$TU --repo "$FIX" --impact --since deadbeefb0gusref >/dev/null 2>&1; rc=$?; [ "$rc" -eq 2 ] && ok "MED: --impact --since <bad ref> exits 2 (distinct from 0 impact)" || no "bad --since ref must exit 2"

# T13 — HIGH-4: --help and unknown args WRITE NOTHING into the target repo
H="$(mktemp -d)"; git -C "$H" init -q
$TU --repo "$H" --help >/dev/null 2>&1; rc=$?;  { [ "$rc" -eq 0 ] && [ ! -e "$H/.true-up" ]; } && ok "HIGH-4: --help exits 0 and writes nothing" || no "HIGH-4: --help must not write"
$TU --repo "$H" --bogus >/dev/null 2>&1; rc=$?; { [ "$rc" -eq 2 ] && [ ! -e "$H/.true-up" ]; } && ok "HIGH-4: unknown command exits 2 and writes nothing" || no "HIGH-4: unknown arg must exit 2, no write"
$TU --repo "$H" >/dev/null 2>&1; [ -e "$H/.true-up/depgraph.json" ] && ok "build (no args) still writes the graph" || no "build must write"

# T14 — HIGH-3: --check --committed is the real drift gate (untracked / stale committed blob both fail)
C="$(mktemp -d)"; git -C "$C" init -q
printf '%s\n' '{ "items": [ { "id": "a", "v": 1 } ] }' > "$C/data.json"
printf '%s\n' '{ "facts": { "data.json": [["items","id"]] }, "zones": [ {"path":"","visibility":"public","audience":"world","intent":"public","rules":["no-machine-local-paths"]} ], "seed": [] }' > "$C/.true-up.json"
git -C "$C" add -A && git -C "$C" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$C" >/dev/null 2>&1
$TU --repo "$C" --check --committed >/dev/null 2>&1; rc=$?; [ "$rc" -ne 0 ] && ok "HIGH-3: --check --committed FAILS when the graph is untracked" || no "HIGH-3: untracked graph must fail --committed"
$TU --repo "$C" --check >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "HIGH-3: plain --check (working-tree freshness) passes on a fresh on-disk graph" || no "HIGH-3: worktree --check must pass when fresh"
git -C "$C" add .true-up/depgraph.json && git -C "$C" -c user.email=t@t -c user.name=t commit -qm graph
$TU --repo "$C" --check --committed >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "HIGH-3: --check --committed passes when the committed graph is fresh" || no "HIGH-3: fresh committed graph must pass"
printf '%s\n' '{ "items": [ { "id": "a", "v": 999 } ] }' > "$C/data.json"
$TU --repo "$C" --check --committed >/dev/null 2>&1; rc=$?; [ "$rc" -ne 0 ] && ok "HIGH-3: --check --committed catches a STALE committed blob" || no "HIGH-3: stale committed graph must fail"

# T15 — LIMITATION fix: a declared (seed) edge to a code file (e.g. .py) is not silently dropped
P="$(mktemp -d)"; git -C "$P" init -q
printf '%s\n' 'def f(): pass' > "$P/registry.py"
printf '%s\n' '# doc' 'derived from the registry' > "$P/doc.md"
printf '%s\n' '{ "zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}], "seed":[ {"from":"doc.md","to":"registry.py","kind":"derives-facts-from"} ] }' > "$P/.true-up.json"
git -C "$P" add -A && git -C "$P" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$P" >/dev/null 2>&1
grep -q 'registry.py' "$P/.true-up/depgraph.json" && ok "seed edge to a .py creates a node (edge not dropped)" || no "seed edge to code file must resolve"
$TU --repo "$P" --impact registry.py 2>/dev/null | grep -q 'doc.md' && ok "--impact on a code source shows its dependent" || no "--impact .py must show dependent"

# T16 — init scaffolds a config and refuses to clobber one
E="$(mktemp -d)"; git -C "$E" init -q
$TU --repo "$E" init >/dev/null 2>&1; rc=$?; { [ "$rc" -eq 0 ] && [ -f "$E/.true-up.json" ]; } && ok "init scaffolds .true-up.json" || no "init must write .true-up.json"
# init is IDEMPOTENT: re-running never clobbers an existing config (safety) AND exits 0 (not 1 — exit 1
# means a gate FAILED everywhere else; a benign "already scaffolded" must not collide with that).
printf '{"_sentinel":"keep-me"}' > "$E/.true-up.json"
$TU --repo "$E" init >/dev/null 2>&1; rc=$?; { [ "$rc" -eq 0 ] && grep -q 'keep-me' "$E/.true-up.json"; } && ok "init is idempotent (exit 0) and never clobbers an existing config" || no "init must be idempotent + no-clobber"

# T17 — empty-graph NOTICE: distinguish "nothing changed" from "you declared nothing to track"
out="$($TU --repo "$E" 2>&1)"
echo "$out" | grep -q 'NOTICE' && ok "empty-graph NOTICE warns when nothing is declared (inert graph)" || no "must warn on an inert graph"

# T18 — HIGH-3 hygiene: --check --committed on an untracked graph must not leak raw git "fatal:" noise
# (P's graph was built in T15 but never committed -> untracked). stderr only:
err="$($TU --repo "$P" --check --committed 2>&1 1>/dev/null)"
echo "$err" | grep -q 'fatal:' && no "blob() must suppress git fatal: noise on untracked graph" || ok "--check --committed (untracked) emits no raw git fatal: noise"

# T19 — cross-repo hygiene: a stale-graph regenerate hint must be generic, not an ugly ../.. engine path
# (C's on-disk graph is stale after T14 changed data.json). stderr only:
err="$($TU --repo "$C" --check 2>&1 1>/dev/null)"
echo "$err" | grep -q '\.\./\.\.' && no "cross-repo regenerate hint leaks a ../.. path" || ok "cross-repo regenerate hint is generic (no ../.. path)"

# T20 — --verify-scope: the deterministic anti-code-golf gate (empirically: unguarded LLMs hit the decoy 3/3)
V="$(mktemp -d)"; git -C "$V" init -q
printf '%s\n' '{ "items": [ { "id": "a", "v": 1 } ] }' > "$V/data.json"
printf '%s\n' '# dep' 'a is 1 <!-- fact: data.json#items.a -->' > "$V/dep.md"
printf '%s\n' '# leaf' 'a is mentioned here but is not anchored to any fact.' > "$V/leaf.md"
printf '%s\n' '{ "facts": { "data.json": [["items","id"]] }, "zones": [ {"path":"","visibility":"public","audience":"world","intent":"public","rules":[]} ], "seed": [] }' > "$V/.true-up.json"
node "$TU" --repo "$V" >/dev/null 2>&1
git -C "$V" add -A && git -C "$V" -c user.email=t@t -c user.name=t commit -qm good
# in-scope maintenance: move the fact + update ONLY its anchored dependent
printf '%s\n' '{ "items": [ { "id": "a", "v": 2 } ] }' > "$V/data.json"
printf '%s\n' '# dep' 'a is 2 <!-- fact: data.json#items.a -->' > "$V/dep.md"
$TU --repo "$V" --verify-scope --since HEAD >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "--verify-scope PASSES when edits stay in the blast radius" || no "--verify-scope must pass in-scope edits"
# now ALSO edit the unanchored leaf (the decoy) -> out of scope -> FAIL, naming it
printf '%s\n' '# leaf' 'a is 2 now (an out-of-scope tidy).' > "$V/leaf.md"
out="$($TU --repo "$V" --verify-scope --since HEAD 2>&1)"; rc=$?
{ [ "$rc" -ne 0 ] && echo "$out" | grep -q 'leaf.md'; } && ok "--verify-scope FAILS on an out-of-blast-radius (code-golf) edit, naming it" || no "--verify-scope must catch out-of-scope edits"

# T21 — must-be-ciphertext is STRUCTURE-AWARE: a plaintext file that merely MENTIONS sops must FAIL
M="$(mktemp -d)"; git -C "$M" init -q; mkdir -p "$M/private"
printf '%s\n' '# notes' 'we use sops to encrypt this directory.' > "$M/private/notes.md"
printf '%s\n' '{ "zones": [ {"path":"private/","visibility":"private","audience":"team","intent":"enc","rules":["must-be-ciphertext"]}, {"path":"","visibility":"public","audience":"world","intent":"pub","rules":[]} ] }' > "$M/.true-up.json"
git -C "$M" add -A && git -C "$M" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$M" --policy --report 2>&1 | grep -q 'must-be-ciphertext' && ok "must-be-ciphertext FLAGS plaintext that merely mentions 'sops'" || no "must-be-ciphertext must reject plaintext mentioning sops"
printf '%s\n' 'data: ENC[AES256_GCM,data:Zm9v,iv:YmFy,tag:YmF6,type:str]' 'sops:' '    mac: ENC[AES256_GCM,data:abc,type:str]' > "$M/private/notes.md"
$TU --repo "$M" --policy --report 2>&1 | grep -q 'must-be-ciphertext' && no "real ENC[…] ciphertext must pass must-be-ciphertext" || ok "real ENC[…] ciphertext passes must-be-ciphertext"

# T22 — ergonomics: --version + capabilities (the machine-readable contract, Axiom 9)
$TU --repo "$FIX" --version 2>&1 | grep -qE '[0-9]+\.[0-9]+' && ok "--version prints a version" || no "--version must print a version"
$TU --repo "$FIX" capabilities 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.exit_codes&&d.commands&&d.version?0:1)' && ok "capabilities is valid JSON with version/commands/exit_codes" || no "capabilities must be a valid JSON contract"

# T23 — ergonomics: --json on read-side gates is pure, valid JSON on stdout (Axiom 8/4)
$TU --repo "$FIX" --policy --json --report 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(Array.isArray(d.violations)&&typeof d.count==="number"?0:1)' && ok "--policy --json is valid structured JSON" || no "--policy --json must be valid JSON"
$TU --repo "$FIX" --externalities --json --report 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(Array.isArray(d.hits)?0:1)' && ok "--externalities --json is valid structured JSON" || no "--externalities --json must be valid JSON"
$TU --repo "$FIX" --impact --json 'data.json#items.a' 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(Array.isArray(d.advisory)?0:1)' && ok "--impact --json is valid structured JSON" || no "--impact --json must be valid JSON"

# T24 — ergonomics: a mistyped command gets a 'did you mean' suggestion (Axiom 7 intent inference)
err="$($TU --repo "$FIX" --externalites 2>&1)"; rc=$?
{ [ "$rc" -eq 2 ] && echo "$err" | grep -q 'did you mean: --externalities'; } && ok "did-you-mean suggests the nearest command on a typo" || no "must suggest nearest command on a typo"

# T25 — Tier 1: language-agnostic SPAN ANCHORS make CODE a content-hashed source-of-truth.
# A paired comment-token region (any language; here Python — the .py-is-inert gap) becomes a
# fact node; a doc that anchors to it gets an advisory derives-facts-from edge.
S="$(mktemp -d)"; git -C "$S" init -q
printf '%s\n' '# true-up:anchor id=parse_config' 'def parse_config(path):' '    return load(path)' '# true-up:end id=parse_config' > "$S/parser.py"
printf '%s\n' '# API' 'parse_config loads the config. <!-- fact: parser.py#parse_config -->' > "$S/api.md"
printf '%s\n' '{ "zones": [ {"path":"","visibility":"public","audience":"world","intent":"public","rules":[]} ], "seed": [] }' > "$S/.true-up.json"
git -C "$S" add -A && git -C "$S" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$S" >/dev/null 2>&1 && ok "Tier1: build succeeds with a code span anchor + doc anchor" || no "Tier1: build must succeed with a code span anchor"
$TU --repo "$S" --impact 'parser.py#parse_config' 2>/dev/null | grep -q 'api.md' && ok "Tier1: a doc derives-facts-from a CODE span (language-agnostic)" || no "Tier1: code span fact-edge must resolve"

# T25b — a malformed span is harmless ON ITS OWN (so files can document the token without self-tripping),
# but a doc that ANCHORS to a span which never formed a complete pair FAILS LOUD (unresolved-anchor backstop).
printf '%s\n' '# true-up:anchor id=orphan' 'def f(): return 1' > "$S/lonely.py"
$TU --repo "$S" >/dev/null 2>&1 && ok "Tier1: a lone unclosed span nobody depends on is harmless (no self-trip)" || no "Tier1: lone unclosed span must not fail the build"
printf '%s\n' 'see <!-- fact: lonely.py#orphan -->' > "$S/needsit.md"
out="$($TU --repo "$S" 2>&1)"; rc=$?
{ [ "$rc" -ne 0 ] && echo "$out" | grep -q 'lonely.py#orphan'; } && ok "Tier1: a doc anchoring to a non-formed span FAILS LOUD (names it)" || no "Tier1: anchor to a missing span must fail-loud"
rm -f "$S/lonely.py" "$S/needsit.md"; $TU --repo "$S" >/dev/null 2>&1

# T25c — INCIDENT guard (mirror of T5b): span-anchor EXAMPLES inside markdown code formatting
# (a doc explaining THIS feature) must NOT be parsed as live spans.
printf '%s\n' '# how-to' 'Bracket a region:' '```' '# true-up:anchor id=demo' 'code here' '# true-up:end id=demo' '```' > "$S/howto.md"
$TU --repo "$S" >/dev/null 2>&1 && ok "Tier1: span examples in markdown code fences do not fail-loud" || no "Tier1: fenced span examples must not fail-loud"
grep -q 'fact:howto.md#demo' "$S/.true-up/depgraph.json" && no "Tier1: a fenced span example must NOT create a live fact node" || ok "Tier1: fenced span example is inert (no spurious fact node)"
rm -f "$S/howto.md"; $TU --repo "$S" >/dev/null 2>&1

# T25d — EARLY-CUTOFF for span facts: editing a span's BODY stales its anchored doc via --since;
# editing the file OUTSIDE the span does NOT (the whole point of fact-granular hashing).
git -C "$S" checkout -- parser.py 2>/dev/null
printf '%s\n' '# true-up:anchor id=parse_config' 'def parse_config(path):' '    return load2(path)  # body changed' '# true-up:end id=parse_config' > "$S/parser.py"
$TU --repo "$S" >/dev/null 2>&1
$TU --repo "$S" --impact --since HEAD 2>/dev/null | grep -q 'api.md' && ok "Tier1: editing a span BODY stales its anchored doc (--since early-cutoff)" || no "Tier1: span-body change must stale the doc via --since"
git -C "$S" checkout -- parser.py 2>/dev/null
printf '%s\n' '# true-up:anchor id=parse_config' 'def parse_config(path):' '    return load(path)' '# true-up:end id=parse_config' '' 'def unrelated(): pass  # outside the span' > "$S/parser.py"
$TU --repo "$S" >/dev/null 2>&1
$TU --repo "$S" --impact --since HEAD 2>/dev/null | grep -q 'api.md' && no "Tier1: an edit OUTSIDE the span must NOT stale the doc (early-cutoff)" || ok "Tier1: edit outside the span does not stale the doc (early-cutoff)"
git -C "$S" checkout -- parser.py 2>/dev/null; $TU --repo "$S" >/dev/null 2>&1

# T25e — a repo whose ONLY facts come from span anchors (no config "facts") is NOT inert: it has
# real edges, so build must NOT cry INERT (the dogfood bug: `inert` ignored span facts).
out="$($TU --repo "$S" 2>&1)"
echo "$out" | grep -q 'INERT' && no "Tier1: a span-anchored repo must NOT be reported INERT" || ok "Tier1: span-anchored repo is not INERT (has real edges)"

# T26 — Tier 2: tree-sitter SYMBOL extraction (config-driven "symbols": true) auto-lifts code
# definitions to fact nodes with NO manual markers; a doc anchors to a symbol by name. (Opt-in,
# optional dependency; the zero-dep core never loads tree-sitter.)
# GUARD: Tier-2 needs the optional tree-sitter devDeps. On a bare clone they're absent — SKIP these
# (honest), don't FAIL. `npm install` (or `bun install`) pulls them and these run for real. This makes
# a fresh `git clone && npm test` GREEN instead of 4 cryptic failures that read like a broken tool.
if [ "$HAS_TS" = 1 ]; then
Y="$(mktemp -d)"; git -C "$Y" init -q
printf '%s\n' 'import os' '' 'def parse_config(path):' '    return load(path)' '' 'class Cfg:' '    def get(self):' '        return 1' > "$Y/app.py"
printf '%s\n' '# Guide' 'parse_config reads the config. <!-- fact: app.py#parse_config -->' > "$Y/guide.md"
printf '%s\n' '{ "symbols": true, "zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}], "seed":[] }' > "$Y/.true-up.json"
git -C "$Y" add -A && git -C "$Y" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$Y" >/dev/null 2>&1 && ok "Tier2: build succeeds with symbols enabled + a symbol anchor" || no "Tier2: symbols build must succeed"
$TU --repo "$Y" --impact 'app.py#parse_config' 2>/dev/null | grep -q 'guide.md' && ok "Tier2: a doc derives-facts-from an auto-extracted CODE SYMBOL (tree-sitter)" || no "Tier2: symbol fact-edge must resolve"

# T27 — Tier 2 EARLY-CUTOFF: editing a SYMBOL's body stales docs anchored to THAT symbol via --since;
# editing a different symbol does not (symbol-granular hashing).
git -C "$Y" add -A && git -C "$Y" -c user.email=t@t -c user.name=t commit -qm base
printf '%s\n' 'import os' '' 'def parse_config(path):' '    return load2(path)  # changed' '' 'class Cfg:' '    def get(self):' '        return 1' > "$Y/app.py"
$TU --repo "$Y" >/dev/null 2>&1
$TU --repo "$Y" --impact --since HEAD 2>/dev/null | grep -q 'guide.md' && ok "Tier2: editing a symbol BODY stales its anchored doc (--since)" || no "Tier2: symbol body change must stale the doc"
git -C "$Y" checkout -- app.py 2>/dev/null
printf '%s\n' 'import os' '' 'def parse_config(path):' '    return load(path)' '' 'class Cfg:' '    def get(self):' '        return 1' '' 'def helper():' '    return 2' > "$Y/app.py"
$TU --repo "$Y" >/dev/null 2>&1
$TU --repo "$Y" --impact --since HEAD 2>/dev/null | grep -q 'guide.md' && no "Tier2: editing a DIFFERENT symbol must NOT stale the doc (early-cutoff)" || ok "Tier2: edit of an unrelated symbol does not stale the doc"
git -C "$Y" checkout -- app.py 2>/dev/null; $TU --repo "$Y" >/dev/null 2>&1

# T28 — Tier 2 is genuinely multi-language: a C++ function's name lives in a DECLARATOR (not a name
# field), exercising the harder extraction path (geometry-central, the top dogfood gap, is C++).
Z="$(mktemp -d)"; git -C "$Z" init -q
printf '%s\n' '#include <string>' '' 'int parse_input(const char* p) {' '    return 0;' '}' > "$Z/api.cpp"
printf '%s\n' '# Docs' 'parse_input returns a status code. <!-- fact: api.cpp#parse_input -->' > "$Z/docs.md"
printf '%s\n' '{ "symbols": true, "zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}], "seed":[] }' > "$Z/.true-up.json"
git -C "$Z" add -A && git -C "$Z" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$Z" >/dev/null 2>&1
$TU --repo "$Z" --impact 'api.cpp#parse_input' 2>/dev/null | grep -q 'docs.md' && ok "Tier2: C++ function symbol extracted via declarator + anchored (multi-language)" || no "Tier2: C++ symbol must resolve"
else
  sk "Tier2 symbol tests (T26-T28): tree-sitter optional devDeps not installed — run \`npm install\` to enable"
fi

# T29 — P0 (ergonomics): per-command flag validation. A typo'd flag must be REJECTED (exit 2 +
# did-you-mean), never silently dropped. The worst case: --comitted downgrades the committed drift
# gate to the worktree check (exit 1→0) — a one-char typo defeating a CI gate. (verified live)
G="$(mktemp -d)"; git -C "$G" init -q
printf '%s\n' '{ "items": [ { "id": "a", "v": 1 } ] }' > "$G/data.json"
printf '%s\n' '{ "facts": { "data.json": [["items","id"]] }, "zones": [ {"path":"","visibility":"public","audience":"world","intent":"public","rules":[]} ], "seed": [] }' > "$G/.true-up.json"
git -C "$G" add -A && git -C "$G" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$G" >/dev/null 2>&1
git -C "$G" add .true-up/depgraph.json && git -C "$G" -c user.email=t@t -c user.name=t commit -qm graph
printf '%s\n' '{ "items": [ { "id": "a", "v": 999 } ] }' > "$G/data.json"
$TU --repo "$G" >/dev/null 2>&1   # worktree graph fresh, committed blob now stale
out="$($TU --repo "$G" --check --comitted 2>&1)"; rc=$?
{ [ "$rc" -eq 2 ] && echo "$out" | grep -q 'did you mean: --committed'; } && ok "P0: --comitted typo is REJECTED (exit 2 + did-you-mean), not a silent gate downgrade" || no "P0: --comitted must not silently downgrade the committed gate"
$TU --repo "$G" --impact --snice HEAD~1 >/dev/null 2>&1; rc=$?; [ "$rc" -eq 2 ] && ok "P0: --impact --snice (typo) exits 2, not a bogus positional '0 dependents'" || no "P0: --impact typo flag must exit 2"
$TU --repo "$G" --check --committed >/dev/null 2>&1; rc=$?; [ "$rc" -ne 2 ] && ok "P0: legit --committed still accepted (validator does not over-reject)" || no "P0: validator must not reject legit flags"

# T30 — P1 (ergonomics): the rebuild hint must be runnable. Against true-up's OWN repo, relative(self)
# is 'lib/engine.mjs' (no '..'), which is not executable — copy-paste → exit 126. Hint must say true-up.
err="$(cd "$HERE" && node bin/true-up bogus 2>&1)"
echo "$err" | grep -qE 'engine\.mjs|^lib/' && no "P1: self error-hint must not name the non-runnable engine path" || ok "P1: in-repo error hint is runnable (not lib/engine.mjs)"

# T31 — P0 (ergonomics): run --json and --version --json must emit JSON (the contract capabilities
# advertises). run is the mega-command agents script with | jq; both emitted human text. (verified)
$TU --repo "$FIX" run --since HEAD --json 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(typeof d.green==="boolean"&&d.verify?0:1)' && ok "P0: run --json is valid structured JSON" || no "P0: run --json must be valid JSON"
$TU --repo "$FIX" --version --json 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.version?0:1)' && ok "P0: --version --json is valid JSON" || no "P0: --version --json must be valid JSON"

# T32 — adoption: `true-up hooks` wires a per-repo gate. --install writes executable pre-commit +
# pre-push hooks running the leak/zone gate; idempotent; the installed hook actually BLOCKS a leak;
# --ci prints a version-pinned snippet; --uninstall removes only the managed hooks.
K="$(mktemp -d)"; git -C "$K" init -q
printf '%s' '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":["no-machine-local-paths"]}]}' > "$K/.true-up.json"
git -C "$K" add -A && git -C "$K" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$K" hooks --install >/dev/null 2>&1
{ [ -x "$K/.git/hooks/pre-commit" ] && [ -x "$K/.git/hooks/pre-push" ]; } && ok "hooks: --install writes executable pre-commit + pre-push" || no "hooks --install must write executable hooks"
{ grep -q 'true-up --policy' "$K/.git/hooks/pre-commit" && grep -q 'true-up --externalities' "$K/.git/hooks/pre-commit"; } && ok "hooks: the gate runs --policy + --externalities" || no "hook must run the gates"
$TU --repo "$K" hooks --install >/dev/null 2>&1
[ "$(grep -c 'managed-by: true-up-hooks' "$K/.git/hooks/pre-commit")" -eq 1 ] && ok "hooks: --install is idempotent (no stacking)" || no "hooks --install must be idempotent"
mkdir -p "$K/shim"; printf '%s\n' '#!/bin/sh' "exec node \"$HERE/bin/true-up\" \"\$@\"" > "$K/shim/true-up"; chmod +x "$K/shim/true-up"
printf '%s\n' 'see /home/somebody/secret/x' > "$K/leak.md"; git -C "$K" add leak.md
if PATH="$K/shim:$PATH" git -C "$K" -c user.email=t@t -c user.name=t commit -qm leak >/dev/null 2>&1; then no "hooks: pre-commit must BLOCK a leak commit"; else ok "hooks: the installed pre-commit BLOCKS a commit that adds a machine-local-path leak"; fi
git -C "$K" reset -q HEAD leak.md 2>/dev/null; rm -f "$K/leak.md"
$TU --repo "$K" hooks --ci 2>/dev/null | grep -q 'npx true-up@' && ok "hooks: --ci prints a version-pinned CI snippet" || no "hooks --ci must print a CI snippet"
$TU --repo "$K" hooks --uninstall >/dev/null 2>&1
{ [ ! -e "$K/.git/hooks/pre-commit" ] && [ ! -e "$K/.git/hooks/pre-push" ]; } && ok "hooks: --uninstall removes the managed hooks" || no "hooks --uninstall must remove them"

# T33 — gate: one CI stage = --check + --policy + --externalities; exit code is authoritative (a runner
# keys on it, not stdout). Exits 0 when clean, nonzero when ANY sub-check fails; --json per-check status.
$TU --repo "$FIX" >/dev/null 2>&1
$TU --repo "$FIX" gate >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "gate: exits 0 on a clean repo (check+policy+externalities)" || no "gate must pass when clean"
$TU --repo "$FIX" gate --json 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.ok===true&&d.checks&&typeof d.checks.policy==="boolean"?0:1)' && ok "gate --json reports per-check status" || no "gate --json must be structured"
printf '%s\n' 'leak /home/someone/y/z' > "$FIX/gateleak.md"
$TU --repo "$FIX" gate >/dev/null 2>&1; rc=$?; [ "$rc" -ne 0 ] && ok "gate: EXITS NONZERO when a sub-check fails (a leak)" || no "gate must fail on any sub-check failure"
rm -f "$FIX/gateleak.md"; $TU --repo "$FIX" >/dev/null 2>&1

# T34 — strictSpans (consumer ask): "strictSpans": true makes a malformed span anchor FATAL so a CI
# gate can't be fooled by a silently-dropped span; default stays lenient (no self-trip on doc'd tokens).
printf '%s' '{"strictSpans":true,"zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}]}' > "$K/.true-up.json"
printf '%s\n' '# true-up:anchor id=dup' 'a' '# true-up:end id=dup' '# true-up:anchor id=dup' 'b' '# true-up:end id=dup' > "$K/dup.py"
out="$($TU --repo "$K" 2>&1)"; rc=$?
{ [ "$rc" -ne 0 ] && echo "$out" | grep -q 'dup'; } && ok "strictSpans: a malformed span (duplicate id) FAILS the build (names it)" || no "strictSpans must fail on a malformed span"
printf '%s' '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}]}' > "$K/.true-up.json"
$TU --repo "$K" >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "default (no strictSpans): the same malformed span is lenient (no self-trip)" || no "default must stay lenient on malformed spans"
rm -f "$K/dup.py"

# T35 — THE READ-ONLY INVARIANT (keystone): no read-side command may modify, create, or delete ANY
# file outside .true-up/ (and .git/). This turns "true-up never touches your content — it writes only
# its own .true-up/ graph (+ .git/hooks on explicit hooks --install)" from a claim into an enforced gate.
# The before/after content hash subsumes a marker-injection check: an injected <!-- fact: -->/true-up:anchor
# would BE a content-byte change and trip this. --no-write build is included (must also touch nothing).
fp(){ ( cd "$1" && find . -type f -not -path './.git/*' -not -path './.true-up/*' | sort | while read -r f; do printf '%s:' "$f"; sha256sum "$f" | cut -d' ' -f1; done ); }
RO_OK=1
for cmd in "" "--no-write" "--check" "--impact data.json#items.a" "--policy --report" "--externalities --report" "--verify-scope --since HEAD" "gate" "capabilities" "--version" "--help"; do
  b="$(fp "$FIX")"; $TU --repo "$FIX" $cmd >/dev/null 2>&1; a="$(fp "$FIX")"
  [ "$b" = "$a" ] || { RO_OK=0; printf '    content CHANGED by: true-up %s\n' "${cmd:-(build)}"; }
done
[ "$RO_OK" = 1 ] && ok "INVARIANT: no read-side command touches any content file (writes only .true-up/)" || no "read-side commands must not modify content outside .true-up/"
[ -f "$FIX/.true-up/depgraph.json" ] && ok "INVARIANT: build's only write is its graph under .true-up/" || no "build must write its graph under .true-up/"

# T36 — MARKER-FREE fact-granular seed: a doc depends on a SPECIFIC fact via .true-up.json `seed`
# (to: path#fact), with NO inline <!-- fact: --> marker in the doc. Early-cutoff must still hold.
SD="$(mktemp -d)"; git -C "$SD" init -q
printf '%s\n' '{ "items": [ { "id": "a", "v": 1 }, { "id": "b", "v": 2 } ] }' > "$SD/data.json"
printf '%s\n' '# Guide' 'a is 1.' > "$SD/doc.md"   # deliberately NO inline anchor
printf '%s' '{ "facts": { "data.json": [["items","id"]] }, "zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}], "seed":[ {"from":"doc.md","to":"data.json#items.a","kind":"derives-facts-from"} ] }' > "$SD/.true-up.json"
git -C "$SD" add -A && git -C "$SD" -c user.email=t@t -c user.name=t commit -qm i
$TU --repo "$SD" >/dev/null 2>&1
$TU --repo "$SD" --impact 'data.json#items.a' 2>/dev/null | grep -q 'doc.md' && ok "marker-free: a fact-granular seed links doc→fact with NO inline marker" || no "fact-granular seed must resolve marker-free"
git -C "$SD" add -A && git -C "$SD" -c user.email=t@t -c user.name=t commit -qm base
printf '%s\n' '{ "items": [ { "id": "a", "v": 1 }, { "id": "b", "v": 999 } ] }' > "$SD/data.json"
$TU --repo "$SD" >/dev/null 2>&1
$TU --repo "$SD" --impact --since HEAD 2>/dev/null | grep -q 'doc.md' && no "marker-free seed early-cutoff: an unrelated fact (items.b) must NOT stale doc.md" || ok "marker-free seed: early-cutoff holds (unrelated fact change does not stale the doc)"
git -C "$SD" checkout -- data.json 2>/dev/null
printf '%s\n' '{ "items": [ { "id": "a", "v": 5 }, { "id": "b", "v": 2 } ] }' > "$SD/data.json"
$TU --repo "$SD" >/dev/null 2>&1
$TU --repo "$SD" --impact --since HEAD 2>/dev/null | grep -q 'doc.md' && ok "marker-free seed: changing the CITED fact stales the doc (--since)" || no "marker-free seed: cited-fact change must stale the doc"
git -C "$SD" checkout -- data.json 2>/dev/null; $TU --repo "$SD" >/dev/null 2>&1

# T37 — fail-loud parity: a seed `to` naming a nonexistent fact or file is a hard error, not a
# silently-dropped edge (closes the one place sidecar edges were LESS safe than inline anchors).
printf '%s' '{ "facts": { "data.json": [["items","id"]] }, "zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}], "seed":[ {"from":"doc.md","to":"data.json#items.NOPE"} ] }' > "$SD/.true-up.json"
out="$($TU --repo "$SD" 2>&1)"; rc=$?
{ [ "$rc" -ne 0 ] && echo "$out" | grep -q 'NOPE'; } && ok "fail-loud: a seed to a nonexistent fact errors (names it)" || no "bad seed fact target must fail-loud"
printf '%s' '{ "zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}], "seed":[ {"from":"doc.md","to":"gone.json"} ] }' > "$SD/.true-up.json"
out="$($TU --repo "$SD" 2>&1)"; rc=$?
{ [ "$rc" -ne 0 ] && echo "$out" | grep -q 'gone.json'; } && ok "fail-loud: a seed to a nonexistent file errors (names it)" || no "bad seed file target must fail-loud"

# T38 — --no-write: a fully-stateless audit that writes NOTHING — not even .true-up/. Query commands
# fall back to an in-memory build instead of "build the graph first". (The owner's "truly no file edits".)
rm -f "$FIX/.true-up/depgraph.json"; rmdir "$FIX/.true-up" 2>/dev/null
$TU --repo "$FIX" --no-write >/dev/null 2>&1; rc=$?
{ [ "$rc" -eq 0 ] && [ ! -e "$FIX/.true-up" ]; } && ok "--no-write: bare build writes NOTHING (no .true-up/ created)" || no "--no-write must not create .true-up/"
$TU --repo "$FIX" --impact 'data.json#items.a' --no-write 2>/dev/null | grep -q 'doc.md' && ok "--no-write: --impact resolves via in-memory build (no on-disk graph, no exit 2)" || no "--impact --no-write must resolve in-memory"
[ ! -e "$FIX/.true-up" ] && ok "--no-write: --impact wrote nothing either" || no "--impact --no-write must not write"
$TU --repo "$FIX" --no-write --json 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.wrote===false&&d.graph&&Array.isArray(d.graph.edges)?0:1)' && ok "--no-write --json emits the in-memory graph (wrote:false)" || no "--no-write --json must emit the graph"
$TU --repo "$FIX" >/dev/null 2>&1   # restore the on-disk graph for any later use

# T39 — DETERMINISM: two builds over an unchanged tree produce a byte-identical graph (sorted, no
# timestamps) — the basis of an honest --check and of --check --committed being the verify gate.
$TU --repo "$FIX" >/dev/null 2>&1; g1="$(mktemp)"; cp "$FIX/.true-up/depgraph.json" "$g1"
$TU --repo "$FIX" >/dev/null 2>&1
cmp -s "$FIX/.true-up/depgraph.json" "$g1" && ok "DETERMINISM: rebuild is byte-identical (honest --check)" || no "build must be byte-deterministic"
rm -f "$g1"

# ============================================================================
# HARDENING REGRESSIONS (v0.1.0 usability + safety pass). Provenance: a 6-lens audit + dogfooding.
# Each case guards one fix so the failure mode can never silently return.
# ============================================================================

# T40 — resolveRoot normalizes --repo to the git TOPLEVEL: a --repo at a SUBDIR must still see the
# toplevel config and CATCH a toplevel leak. (GAP-H: subdir --repo saw an empty graph → false-clean.)
RR="$(mktemp -d)"; git -C "$RR" init -q; mkdir -p "$RR/pkg/deep"
printf '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"p","rules":["no-machine-local-paths"]}]}' > "$RR/.true-up.json"
printf 'see /home/victim/secret/x\n' > "$RR/README.md"
git -C "$RR" add -A && git -C "$RR" -c user.email=t@t -c user.name=t commit -qm i
$TU --repo "$RR/pkg" --externalities >/dev/null 2>&1; rc=$?; [ "$rc" -eq 1 ] && ok "resolveRoot: --repo <subdir> normalizes to toplevel + catches a toplevel leak (no GAP-H false-clean)" || no "resolveRoot must normalize --repo subdir to toplevel (rc=$rc)"

# T41 — a non-git --repo is a CLEAN exit 2, never a false-clean scan of an empty file set. (GAP-F.)
NG="$(mktemp -d)"; printf 'leak /home/victim/secret/y\n' > "$NG/README.md"
out="$($TU --repo "$NG" --externalities 2>&1)"; rc=$?; { [ "$rc" -eq 2 ] && ! echo "$out" | grep -q 'clean'; } && ok "resolveRoot: --repo <non-git dir> exits 2 (no false-clean)" || no "non-git --repo must exit 2 (rc=$rc)"

# T42 — a nonexistent --repo exits 2 with ONE clean line, not raw git 'fatal:' noise. (ROOT-6/ROOT-8.)
out="$($TU --repo /no/such/path/xyz --policy 2>&1)"; rc=$?; { [ "$rc" -eq 2 ] && ! echo "$out" | grep -q 'fatal:'; } && ok "resolveRoot: nonexistent --repo exits 2, no raw git fatal: noise" || no "nonexistent --repo must exit 2 cleanly (rc=$rc)"

# T43 — --version is CLEAN outside any git repo (no eager-ROOT 'fatal:' leak to stderr). (ROOT-8.)
ND="$(mktemp -d)"; out="$(cd "$ND" && $TU --version 2>&1)"; { echo "$out" | grep -qE '[0-9]+\.[0-9]+' && ! echo "$out" | grep -q 'fatal:'; } && ok "--version outside a git repo prints cleanly (no git fatal: leak)" || no "--version must be clean outside a repo"

# T44 — hooks SAFETY: with core.hooksPath pointing OUTSIDE the repo, --install REFUSES (exit 2) and does
# NOT write there; --force is the explicit opt-in. This is the footgun that clobbered a dev's GLOBAL
# hooks during `npm test`. (Isolated fake-global config for this case only.)
HKEXT="$(mktemp -d)"; FAKEG="$(mktemp)"; printf '[core]\n\thooksPath = %s\n' "$HKEXT" > "$FAKEG"
HX="$(mktemp -d)"; GIT_CONFIG_GLOBAL="$FAKEG" git -C "$HX" init -q
printf '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"p","rules":[]}]}' > "$HX/.true-up.json"
GIT_CONFIG_GLOBAL="$FAKEG" git -C "$HX" add -A && GIT_CONFIG_GLOBAL="$FAKEG" git -C "$HX" -c user.email=t@t -c user.name=t commit -qm i
GIT_CONFIG_GLOBAL="$FAKEG" $TU --repo "$HX" hooks --install >/dev/null 2>&1; rc=$?
{ [ "$rc" -eq 2 ] && [ -z "$(ls -A "$HKEXT")" ]; } && ok "hooks: REFUSES install into an out-of-repo (global) hooks dir; external dir untouched" || no "hooks must refuse external hooksPath without --force (rc=$rc)"
GIT_CONFIG_GLOBAL="$FAKEG" $TU --repo "$HX" hooks --install --force >/dev/null 2>&1; rc=$?
{ [ "$rc" -eq 0 ] && [ -f "$HKEXT/pre-commit" ]; } && ok "hooks: --force writes into the external dir (explicit opt-in)" || no "hooks --force must allow external install (rc=$rc)"

# T45 — hooks SAFETY: --uninstall RESTORES the foreign hook backed up on install (no silent loss).
HR="$(mktemp -d)"; git -C "$HR" init -q
printf '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"p","rules":[]}]}' > "$HR/.true-up.json"
printf '#!/bin/sh\necho ORIGINAL-FOREIGN-HOOK\n' > "$HR/.git/hooks/pre-commit"; chmod +x "$HR/.git/hooks/pre-commit"
$TU --repo "$HR" hooks --install >/dev/null 2>&1
$TU --repo "$HR" hooks --uninstall >/dev/null 2>&1
{ grep -q 'ORIGINAL-FOREIGN-HOOK' "$HR/.git/hooks/pre-commit" 2>/dev/null && [ ! -f "$HR/.git/hooks/pre-commit.bak" ]; } && ok "hooks: --uninstall restores the backed-up foreign hook (no silent loss) + clears .bak" || no "hooks --uninstall must restore the original hook"

# T32b — hooks land INSIDE the test repo under isolation (proves the harness is hermetic; if this fails,
# the suite is touching a shared/global hooks dir again — STOP and re-read the isolation block).
HI="$(mktemp -d)"; git -C "$HI" init -q
printf '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"p","rules":[]}]}' > "$HI/.true-up.json"
$TU --repo "$HI" hooks --install >/dev/null 2>&1
[ -f "$HI/.git/hooks/pre-commit" ] && ok "hermetic: hooks --install writes INSIDE the repo's .git (harness isolation holds)" || no "harness isolation broken — hooks landed outside the repo"

# T46 — config FAIL-LOUD: a malformed .true-up.json is exit 2 (not swallowed → false-clean), with NO
# stack trace (a trace would leak the engine's own absolute path — ironic for a leak detector). ROOT-11.
BC="$(mktemp -d)"; git -C "$BC" init -q; printf '{ not json' > "$BC/.true-up.json"
printf 'x\n' > "$BC/a.md"; git -C "$BC" add -A && git -C "$BC" -c user.email=t@t -c user.name=t commit -qm i
out="$($TU --repo "$BC" --externalities 2>&1)"; rc=$?; { [ "$rc" -eq 2 ] && ! echo "$out" | grep -q 'engine.mjs'; } && ok "config: malformed .true-up.json exits 2 cleanly (no swallow, no stack trace)" || no "malformed config must fail loud + clean (rc=$rc)"

# T47 — config SHAPE validation: an ill-typed key exits 2 cleanly (was an uncaught TypeError stack). GAP-G.
WC="$(mktemp -d)"; git -C "$WC" init -q; printf '{"zones":"public"}' > "$WC/.true-up.json"
git -C "$WC" add -A && git -C "$WC" -c user.email=t@t -c user.name=t commit -qm i
out="$($TU --repo "$WC" --policy 2>&1)"; rc=$?; { [ "$rc" -eq 2 ] && ! echo "$out" | grep -q 'engine.mjs'; } && ok "config: ill-typed \"zones\" exits 2 cleanly (no TypeError stack trace)" || no "ill-typed config key must exit 2 cleanly (rc=$rc)"

# T48 — write-invariant: `out` must not escape the repo (../) nor overwrite a tracked content file. ROOT-4.
OE="$(mktemp -d)"; git -C "$OE" init -q; printf '{"out":"../escape.json"}' > "$OE/.true-up.json"
printf 'x\n' > "$OE/a.md"; git -C "$OE" add -A && git -C "$OE" -c user.email=t@t -c user.name=t commit -qm i
$TU --repo "$OE" >/dev/null 2>&1; rc=$?; { [ "$rc" -eq 2 ] && [ ! -f "$OE/../escape.json" ]; } && ok "out: a '../' path is REFUSED (exit 2); nothing written outside the repo" || no "out must not escape the repo (rc=$rc)"
OC="$(mktemp -d)"; git -C "$OC" init -q; printf 'KEEP-ME README\n' > "$OC/README.md"; printf '{"out":"README.md"}' > "$OC/.true-up.json"
git -C "$OC" add -A && git -C "$OC" -c user.email=t@t -c user.name=t commit -qm i
$TU --repo "$OC" >/dev/null 2>&1; rc=$?; { [ "$rc" -eq 2 ] && grep -q 'KEEP-ME' "$OC/README.md"; } && ok "out: refuses to overwrite a tracked content file (README intact)" || no "out must not overwrite tracked content (rc=$rc)"

# T49 — --impact on an UNKNOWN target is a usage ERROR (exit 2), not a silent "0 dependents". ROOT-7.
IT="$(mktemp -d)"; git -C "$IT" init -q
printf '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"p","rules":[]}]}' > "$IT/.true-up.json"
printf 'a\n' > "$IT/a.md"; git -C "$IT" add -A && git -C "$IT" -c user.email=t@t -c user.name=t commit -qm i
$TU --repo "$IT" >/dev/null 2>&1
$TU --repo "$IT" --impact does/not/exist.md >/dev/null 2>&1; rc=$?; [ "$rc" -eq 2 ] && ok "--impact unknown target exits 2 (not a false '0 dependents')" || no "--impact unknown target must exit 2 (rc=$rc)"
# capture-then-parse: the command exits 2, so a `| node` pipe would mask the parse under pipefail (the
# documented pipefail trap). Capture stdout into a var (echo exits 0), then validate the JSON separately.
js="$($TU --repo "$IT" --impact does/not/exist.md --json 2>/dev/null)"; printf '%s' "$js" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.ok===false?0:1)' && ok "--impact unknown target --json emits {ok:false} on stdout (not empty)" || no "--impact --json error must emit JSON"

# T50 — --json error paths emit parseable JSON: a bad --since ref under --json is {ok:false}, not empty. ROOT-5.
js="$($TU --repo "$IT" --impact --since deadbeef --json 2>/dev/null)"; printf '%s' "$js" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.ok===false?0:1)' && ok "--json: a bad --since ref emits {ok:false} on stdout" || no "--json bad-ref must be parseable JSON"

# T51 — --check distinguishes 'not built' from 'stale' so an agent knows to BUILD vs debug a diff.
NB="$(mktemp -d)"; git -C "$NB" init -q
printf '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"p","rules":[]}]}' > "$NB/.true-up.json"
printf 'a\n' > "$NB/a.md"; git -C "$NB" add -A && git -C "$NB" -c user.email=t@t -c user.name=t commit -qm i
js="$($TU --repo "$NB" --check --json 2>/dev/null)"; printf '%s' "$js" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.reason==="not built"&&d.built===false?0:1)' && ok "--check on a never-built repo reports reason:'not built' (not 'stale')" || no "--check must distinguish not-built from stale"

# T52 — run surfaces a failing generator's stderr (was swallowed by stdio:'ignore'). GAP-E.
RG="$(mktemp -d)"; git -C "$RG" init -q
printf '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"p","rules":[]}],"seed":[]}' > "$RG/.true-up.json"
printf 'process.stderr.write("BOOM-IN-GENERATOR\\n"); process.exit(1)\n' > "$RG/gen.mjs"
printf '<!-- generated by gen.mjs from a.json -->\nview\n' > "$RG/view.md"
printf '{"k":1}\n' > "$RG/a.json"
git -C "$RG" add -A && git -C "$RG" -c user.email=t@t -c user.name=t commit -qm i
$TU --repo "$RG" >/dev/null 2>&1
printf '{"k":2}\n' > "$RG/a.json"
out="$($TU --repo "$RG" run --since HEAD 2>&1)"; echo "$out" | grep -q 'BOOM-IN-GENERATOR' && ok "run: a failing generator's stderr is surfaced (not swallowed)" || no "run must surface generator stderr"

# T53 — run refuses to EXECUTE a generator whose path escapes the repo (arbitrary out-of-tree code). P0#5.
RX="$(mktemp -d)"; git -C "$RX" init -q
printf '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"p","rules":[]}],"seed":[]}' > "$RX/.true-up.json"
printf '<!-- generated by ../evil.mjs from a.json -->\nview\n' > "$RX/view.md"
printf '{"k":1}\n' > "$RX/a.json"
git -C "$RX" add -A && git -C "$RX" -c user.email=t@t -c user.name=t commit -qm i
$TU --repo "$RX" >/dev/null 2>&1
printf '{"k":2}\n' > "$RX/a.json"
out="$($TU --repo "$RX" run --since HEAD 2>&1)"; echo "$out" | grep -q 'refusing to run generator OUTSIDE' && ok "run: refuses to execute a generator path that escapes the repo" || no "run must refuse out-of-repo generators"

# ============================================================================
# ERGONOMICS REGRESSIONS (v0.1.0 agent-ergonomics pass). Provenance: agent_ergonomics_audit/ (6-lens scoring).
# ============================================================================

# T64 — `status`: read-only ORIENTATION in one call, ALWAYS exit 0 (a probe, not a gate), writes nothing.
ST="$(mktemp -d)"; git -C "$ST" init -q
printf '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"p","rules":[]}]}' > "$ST/.true-up.json"
printf 'a\n' > "$ST/a.md"; git -C "$ST" add -A && git -C "$ST" -c user.email=t@t -c user.name=t commit -qm i
$TU --repo "$ST" status >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "status exits 0 even when not built (probe, not gate)" || no "status must exit 0 (rc=$rc)"
[ ! -e "$ST/.true-up" ] && ok "status writes nothing (read-only probe)" || no "status mutated the repo"
js="$($TU --repo "$ST" status --json 2>/dev/null)"; printf '%s' "$js" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.ok===true&&d.built===false&&Array.isArray(d.nextCommands)&&d.nextCommands.length>0&&d._v===1?0:1)' && ok "status --json carries ok/built/nextCommands/_v" || no "status --json shape"

# T65 — `build` verb persists the graph (explicit, discoverable alias of bare true-up)
$TU --repo "$ST" build >/dev/null 2>&1; rc=$?; { [ "$rc" -eq 0 ] && [ -f "$ST/.true-up/depgraph.json" ]; } && ok "build verb persists the graph" || no "build must persist (rc=$rc)"

# T66 — `robot-docs`: in-tool handbook, works OUTSIDE a git repo (like --help), writes nothing.
ND2="$(mktemp -d)"; out="$(cd "$ND2" && $TU robot-docs 2>&1)"; rc=$?
{ [ "$rc" -eq 0 ] && echo "$out" | grep -q 'true-up status' && [ -z "$(ls -A "$ND2")" ]; } && ok "robot-docs prints a handbook outside a repo + writes nothing" || no "robot-docs must work anywhere + write nothing (rc=$rc)"

# T67 — intent inference: semantic + cross-prefix + global-flag guesses redirect to the RIGHT command.
# (capture-then-grep: these commands exit 2, so a direct `| grep` would mask the match under pipefail.)
o="$($TU --repo "$FIX" update 2>&1)";       echo "$o" | grep -q 'did you mean: run'        && ok "intent: update → run (synonym, not lexical 'gate')" || no "update→run synonym"
o="$($TU --repo "$FIX" docs 2>&1)";         echo "$o" | grep -q 'did you mean: robot-docs' && ok "intent: docs → robot-docs" || no "docs→robot-docs"
o="$($TU --repo "$FIX" imapct x 2>&1)";     echo "$o" | grep -q -- '--impact'              && ok "intent: imapct → --impact (cross-prefix)" || no "imapct→--impact"
o="$($TU --repo "$FIX" --jsno --check 2>&1)"; echo "$o" | grep -q -- '--json'              && ok "intent: --jsno → --json (global-flag typo)" || no "--jsno→--json"

# T68 — discovery errors honor --json (unknown command/flag emit {ok:false} on stdout, not empty). ROOT-5.
js="$($TU --repo "$FIX" --json zzzcmd 2>/dev/null)"; printf '%s' "$js" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.ok===false&&d.kind==="unknown-command"?0:1)' && ok "unknown-command --json → {ok:false,kind}" || no "unknown-command json"
js="$($TU --repo "$FIX" --json --check --comitted 2>/dev/null)"; printf '%s' "$js" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.kind==="unknown-flag"&&d.didYouMean==="--committed"?0:1)' && ok "unknown-flag --json → kind + didYouMean" || no "unknown-flag json"

# T69 — Axiom 14: a stray positional on a no-positional command is exit 2 (gate zzz no longer PASSes).
$TU --repo "$FIX" gate zzz >/dev/null 2>&1; [ $? -eq 2 ] && ok "gate <stray-arg> exits 2 (no silent PASS)" || no "gate must reject stray positionals"
$TU --repo "$FIX" status extra >/dev/null 2>&1; [ $? -eq 2 ] && ok "status <stray-arg> exits 2" || no "status must reject stray positionals"

# T70 — uniform envelope: every read-side command answers .ok (boolean) + ._v (one jq question works everywhere).
UE="$(mktemp -d)"; git -C "$UE" init -q
printf '{"facts":{"data.json":[["items","id"]]},"zones":[{"path":"","visibility":"public","audience":"world","intent":"p","rules":[]}],"seed":[{"from":"doc.md","to":"data.json#items.a"}]}' > "$UE/.true-up.json"
printf '{"items":[{"id":"a","v":1}]}' > "$UE/data.json"; printf 'a <!-- fact: data.json#items.a -->\n' > "$UE/doc.md"
git -C "$UE" add -A && git -C "$UE" -c user.email=t@t -c user.name=t commit -qm i
$TU --repo "$UE" build >/dev/null 2>&1
ok_v=1
for spec in "--check" "--policy" "--externalities" "--verify-scope" "--impact data.json#items.a" "gate" "status"; do
  js="$($TU --repo "$UE" $spec --json 2>/dev/null)"
  printf '%s' "$js" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(typeof d.ok==="boolean"&&d._v===1?0:1)' || ok_v=0
done
[ "$ok_v" = 1 ] && ok "every read-side command emits .ok (boolean) + ._v (uniform envelope)" || no "read-side envelope must carry .ok + ._v"

# T71 — run --json REAL path carries advisoryWorklist (parity with --no-write; no second --impact call). ROOT-5.
printf '{"items":[{"id":"a","v":2}]}' > "$UE/data.json"
js="$($TU --repo "$UE" run --since HEAD --json 2>/dev/null)"; printf '%s' "$js" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(Array.isArray(d.advisoryWorklist)&&d.advisoryWorklist[0]&&d.advisoryWorklist[0].doc==="doc.md"?0:1)' && ok "run --json (real path) emits advisoryWorklist (doc←fact)" || no "run advisoryWorklist asymmetry"
git -C "$UE" checkout -q data.json 2>/dev/null

# T72 — capabilities completeness (contract-drift guard): quickstart + entrypoints + cmd_flags present;
# every CMD_FLAGS flag visible (so --force/--uninstall can't silently drop); --print gone; new cmds listed.
caps="$($TU --repo "$FIX" capabilities 2>/dev/null)"
printf '%s' "$caps" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));const t=JSON.stringify(d);process.exit(d.quickstart&&d.entrypoints&&d.cmd_flags&&t.includes("--force")&&t.includes("--uninstall")&&!t.includes("--print")?0:1)' && ok "capabilities: quickstart/entrypoints/cmd_flags present; --force/--uninstall documented; --print gone" || no "capabilities contract completeness"
printf '%s' "$caps" | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));const n=d.commands.map(c=>c.name.split(" ")[0]);process.exit(n.includes("status")&&n.includes("build")&&n.includes("robot-docs")?0:1)' && ok "capabilities lists status/build/robot-docs" || no "new commands missing from capabilities"

# T73 — DOCS-IN-SYNC GATE (harness-engineering: true-up's OWN README once went stale — documenting a
# tool whose whole job is keeping things in sync. NEVER AGAIN). The user/agent-facing docs (README.md,
# SKILL.md) MUST document every command in `true-up capabilities`. Add/rename/remove a command without
# updating the docs → this FAILS (in npm test + CI), so a drifted doc can't ship. AGENTS.md (maintainer)
# is tracked separately via the .true-up.json contract seed.
caps_cmds=$($TU capabilities --json 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));const names=d.commands.map(c=>c.name.split(/[ \[]/)[0]).filter(n=>n&&!n.startsWith("("));process.stdout.write([...new Set(names)].join("\n"))')
docs_missing=""
for cmd in $caps_cmds; do
  grep -qF -- "$cmd" "$HERE/README.md" || docs_missing="$docs_missing README:$cmd"
  grep -qF -- "$cmd" "$HERE/SKILL.md"   || docs_missing="$docs_missing SKILL:$cmd"
done
[ -z "$docs_missing" ] && ok "DOCS-IN-SYNC: every \`capabilities\` command is documented in README.md + SKILL.md" || no "docs out of sync — undocumented commands:$docs_missing"

# T74 — MARKER-FREE SELF-DOGFOOD GATE. true-up trues up its OWN repo with ZERO inline markers: every edge
# is a sidecar `seed` (declared) in .true-up.json, or a symlink alias. This was CLAIMED in AGENTS.md but
# never asserted. Now it is: the self-build must have NO 'anchored' or 'generator' edges (the inline-marker
# bases). Drop a <!-- fact: --> or true-up:anchor into a true-up source file and this fails — use a seed.
marker_edges=$($TU --repo "$HERE" --no-write --json 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));const b=d.byDirectionBasis||{};process.stdout.write(String((b.anchored||0)+(b.generator||0)))')
[ "$marker_edges" = "0" ] && ok "MARKER-FREE: true-up's own repo has 0 inline-marker edges (all declared seed / symlink)" || no "true-up's own repo grew an inline-marker edge (anchored+generator=$marker_edges) — declare it as a .true-up.json seed instead"

# ── DOC-TRUTH gates (a doc-fact-check workflow found drift the command-coverage gate was blind to) ──

# T75 — DOCS FLAG-COVERAGE: every per-command flag in capabilities.cmd_flags must be documented in
# README.md (the canonical reference). Catches a flag added to the engine but never documented — the
# `status --committed` class (a flag in the contract that no command actually honored).
caps_flags=$($TU capabilities --json 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));const f=d.cmd_flags||{};const o=[];for(const k of Object.keys(f))for(const fl of f[k])o.push(fl);process.stdout.write([...new Set(o)].join("\n"))')
flags_missing=""
for fl in $caps_flags; do grep -qF -- "$fl" "$HERE/README.md" || flags_missing="$flags_missing $fl"; done
[ -z "$flags_missing" ] && ok "DOCS-FLAGS: every capabilities cmd-flag is documented in README.md" || no "undocumented flags in README:$flags_missing"

# T76 — NO STALE init EXIT-1 CLAIM. init is idempotent (capabilities exits:[0]). PROVE it by running
# init twice, THEN assert no user/agent doc still claims init "refuses to overwrite … exit 1".
IT76="$(mktemp -d)"; git -C "$IT76" init -q
$TU --repo "$IT76" init >/dev/null 2>&1
$TU --repo "$IT76" init >/dev/null 2>&1; rc76=$?
init_bad=""
for f in README.md SKILL.md docs/CONFIG.md; do grep -nE 'refuses to overwrite' "$HERE/$f" 2>/dev/null | grep -qE 'exit 1' && init_bad="$init_bad $f"; done
{ [ "$rc76" -eq 0 ] && [ -z "$init_bad" ]; } && ok "init is idempotent (exit 0) and no doc claims 'refuses to overwrite … exit 1'" || no "init exit-1 drift (second-run rc=$rc76; stale docs:$init_bad)"

# T77 — NO INTERNAL JARGON in user-facing surfaces. Tier 1/Tier 2 and Axiom N are maintainer-only
# (AGENTS.md / CLAUDE.md). Scan the user/agent docs AND the installer's user-visible --help output.
jargon_hits=""
for f in README.md SKILL.md docs/CONFIG.md CHANGELOG.md; do grep -Eq "Tier 1|Tier 2|Axiom [0-9]" "$HERE/$f" 2>/dev/null && jargon_hits="$jargon_hits $f"; done
ihelp="$(bash "$HERE/install.sh" --help 2>/dev/null)"
echo "$ihelp" | grep -Eq "Tier 1|Tier 2|Axiom [0-9]" && jargon_hits="$jargon_hits install.sh(--help)"
[ -z "$jargon_hits" ] && ok "NO-JARGON: user-facing docs + installer --help carry no Tier/Axiom internal jargon" || no "internal jargon leaked to users in:$jargon_hits"

# T78 — INSTALLER --help MUST NOT LEAK SOURCE (the help handler seds a comment range; an over-wide
# range prints real code — the audit caught exactly this).
echo "$ihelp" | grep -qE 'set -euo pipefail|^REPO_SLUG=|umask |shopt -s' && no "install.sh --help leaks source code (sed range overshoots the comment header)" || ok "install.sh --help renders only the comment header (no source leak)"

echo
echo "engine tests: ${pass} passed, ${fail} failed, ${skip} skipped"
[ "$skip" = 0 ] || echo "  (skipped suites need optional devDeps — run \`npm install\` to enable them)"
[ "$fail" = 0 ] || exit 1
