#!/usr/bin/env bash
# tests/engine.sh — fixture-based regression harness for the true-up engine.
#
# Tests ARE the harness. This builds a SYNTHETIC target repo from scratch and runs the
# real CLI against it via --repo, proving true-up is repo-agnostic (config-driven, not
# wired to its own directory) and pinning every load-bearing invariant + incident guard.
# Fast (<60s). Run: bash tests/engine.sh   (or: npm test)
set -uo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
TU="node ${HERE}/bin/true-up"
pass=0 ; fail=0
ok(){ printf '  \033[32mPASS\033[0m %s\n' "$1"; pass=$((pass + 1)); }
no(){ printf '  \033[31mFAIL\033[0m %s\n' "$1"; fail=$((fail + 1)); }

FIX="$(mktemp -d)"
trap 'rm -rf "$FIX"' EXIT

# --- synthesize a target repo: steward data + a generated view + an anchored doc + a symlink ---
git -C "$FIX" init -q
cat > "$FIX/.true-up.json" <<'JSON'
{
  "facts": { "data.json": [["items", "id"]] },
  "zones": [
    { "path": "secret/", "visibility": "private", "audience": "team", "intent": "encrypted-notes", "rules": ["must-be-ciphertext"] },
    { "path": "", "visibility": "public", "audience": "world", "intent": "public-default", "rules": ["no-machine-local-paths"] }
  ],
  "seed": [ { "from": "doc.md", "to": "data.json", "kind": "derives-facts-from" } ]
}
JSON
printf '%s\n' '{ "items": [ { "id": "a", "v": 1 }, { "id": "b", "v": 2 } ] }' > "$FIX/data.json"
printf '%s\n' '# generated view' '<!-- generated by build.mjs from data.json -->' 'a=1 b=2' > "$FIX/gen.md"
printf '%s\n' '# doc' 'item a has value 1.' '<!-- fact: data.json#items.a -->' > "$FIX/doc.md"
ln -s doc.md "$FIX/link.md"
git -C "$FIX" add -A && git -C "$FIX" -c user.email=t@t -c user.name=t commit -qm init

# T1 — engine runs on a FOREIGN repo via --repo, writes into the target
$TU --repo "$FIX" >/dev/null 2>&1 && ok "build runs on a foreign repo (--repo)" || no "build runs on a foreign repo"
[ -f "$FIX/.true-up/depgraph.json" ] && ok "writes .true-up/depgraph.json into the target" || no "writes depgraph.json into target"
$TU --repo "$FIX" --check >/dev/null 2>&1 && ok "--check passes when in sync" || no "--check passes when in sync"

# T2 — config-driven fact nodes + anchored edge resolve (repo-agnostic)
$TU --repo "$FIX" --impact 'data.json#items.a' 2>/dev/null | grep -q 'doc.md' && ok "anchored fact-edge resolves (doc.md <- data.json#items.a)" || no "anchored fact-edge resolves"

# T3/T4 — structural edges from conventions
grep -q 'generated-from' "$FIX/.true-up/depgraph.json" && ok "generated-from edge from self-describing marker" || no "generated-from edge"
grep -q 'alias-of' "$FIX/.true-up/depgraph.json" && ok "symlink alias-of edge (link.md -> doc.md)" || no "symlink alias-of edge"

# T5 — fail-loud on an unresolved fact-anchor
printf '%s\n' '<!-- fact: data.json#items.NOPE -->' > "$FIX/bad.md"
$TU --repo "$FIX" >/dev/null 2>&1 && no "build must FAIL on unresolved anchor" || ok "fail-loud on unresolved anchor"
rm -f "$FIX/bad.md"; $TU --repo "$FIX" >/dev/null 2>&1

# T5b — INCIDENT: anchor/marker EXAMPLES in code formatting (a doc explaining true-up's syntax)
# must NOT be parsed as live anchors (else any repo documenting true-up would fail-loud).
printf '%s\n' '# how-to' 'Anchor inline like `<!-- fact: example.json#x.y -->`, or fenced:' '```' '<!-- fact: another.json#z.w -->' '```' > "$FIX/howto.md"
$TU --repo "$FIX" >/dev/null 2>&1 && ok "anchor examples in code formatting do not fail-loud" || no "anchor examples in code must not fail-loud"
rm -f "$FIX/howto.md"; $TU --repo "$FIX" >/dev/null 2>&1

# T6 — externality detection (machine-local leak)
printf '%s\n' 'path: /home/someuser/x' > "$FIX/leak.md"
$TU --repo "$FIX" --externalities 2>/dev/null | grep -q '\[high\]' && ok "--externalities flags a /home leak" || no "--externalities flags a leak"
rm -f "$FIX/leak.md"
$TU --repo "$FIX" --externalities 2>/dev/null | grep -q ': 0 (0 high)' && ok "--externalities clean otherwise" || no "--externalities clean otherwise"

# T7 — zone/policy gate clean
$TU --repo "$FIX" --policy 2>/dev/null | grep -q 'policy violations: 0' && ok "--policy reports 0 violations" || no "--policy reports 0 violations"

# T8 — the deterministic true-up loop reaches GREEN on a clean target
$TU --repo "$FIX" run --since HEAD 2>/dev/null | grep -q 'GREEN' && ok "run --since reaches GREEN on a clean repo" || no "run reaches GREEN"

echo
echo "engine tests: ${pass} passed, ${fail} failed"
[ "$fail" = 0 ] || exit 1
