#!/usr/bin/env bash
# tests/engine.sh — fixture-based regression harness for the true-up engine.
#
# Tests ARE the harness. This builds a SYNTHETIC target repo from scratch and runs the
# real CLI against it via --repo, proving true-up is repo-agnostic (config-driven, not
# wired to its own directory) and pinning every load-bearing invariant + incident guard.
# Fast (<60s). Run: bash tests/engine.sh   (or: npm test)
set -uo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
TU="node ${HERE}/bin/true-up"
pass=0 ; fail=0
ok(){ printf '  \033[32mPASS\033[0m %s\n' "$1"; pass=$((pass + 1)); }
no(){ printf '  \033[31mFAIL\033[0m %s\n' "$1"; fail=$((fail + 1)); }

FIX="$(mktemp -d)"; H=""; C=""; P=""; E=""; V=""; M=""; S=""; Y=""; Z=""; G=""; K=""
trap 'rm -rf "$FIX" "$H" "$C" "$P" "$E" "$V" "$M" "$S" "$Y" "$Z" "$G" "$K"' EXIT

# --- synthesize a target repo: steward data + a generated view + an anchored doc + a symlink ---
git -C "$FIX" init -q
cat > "$FIX/.true-up.json" <<'JSON'
{
  "facts": { "data.json": [["items", "id"]] },
  "zones": [
    { "path": "secret/", "visibility": "private", "audience": "team", "intent": "encrypted-notes", "rules": ["must-be-ciphertext"] },
    { "path": "", "visibility": "public", "audience": "world", "intent": "public-default", "rules": ["no-machine-local-paths"] }
  ],
  "seed": [ { "from": "doc.md", "to": "data.json", "kind": "derives-facts-from" } ]
}
JSON
printf '%s\n' '{ "items": [ { "id": "a", "v": 1 }, { "id": "b", "v": 2 } ] }' > "$FIX/data.json"
printf '%s\n' '# generated view' '<!-- generated by build.mjs from data.json -->' 'a=1 b=2' > "$FIX/gen.md"
printf '%s\n' '# doc' 'item a has value 1.' '<!-- fact: data.json#items.a -->' > "$FIX/doc.md"
ln -s doc.md "$FIX/link.md"
git -C "$FIX" add -A && git -C "$FIX" -c user.email=t@t -c user.name=t commit -qm init

# T1 — engine runs on a FOREIGN repo via --repo, writes into the target
$TU --repo "$FIX" >/dev/null 2>&1 && ok "build runs on a foreign repo (--repo)" || no "build runs on a foreign repo"
[ -f "$FIX/.true-up/depgraph.json" ] && ok "writes .true-up/depgraph.json into the target" || no "writes depgraph.json into target"
$TU --repo "$FIX" --check >/dev/null 2>&1 && ok "--check passes when in sync" || no "--check passes when in sync"

# T2 — config-driven fact nodes + anchored edge resolve (repo-agnostic)
$TU --repo "$FIX" --impact 'data.json#items.a' 2>/dev/null | grep -q 'doc.md' && ok "anchored fact-edge resolves (doc.md <- data.json#items.a)" || no "anchored fact-edge resolves"

# T3/T4 — structural edges from conventions
grep -q 'generated-from' "$FIX/.true-up/depgraph.json" && ok "generated-from edge from self-describing marker" || no "generated-from edge"
grep -q 'alias-of' "$FIX/.true-up/depgraph.json" && ok "symlink alias-of edge (link.md -> doc.md)" || no "symlink alias-of edge"

# T5 — fail-loud on an unresolved fact-anchor
printf '%s\n' '<!-- fact: data.json#items.NOPE -->' > "$FIX/bad.md"
$TU --repo "$FIX" >/dev/null 2>&1 && no "build must FAIL on unresolved anchor" || ok "fail-loud on unresolved anchor"
rm -f "$FIX/bad.md"; $TU --repo "$FIX" >/dev/null 2>&1

# T5b — INCIDENT: anchor/marker EXAMPLES in code formatting (a doc explaining true-up's syntax)
# must NOT be parsed as live anchors (else any repo documenting true-up would fail-loud).
printf '%s\n' '# how-to' 'Anchor inline like `<!-- fact: example.json#x.y -->`, or fenced:' '```' '<!-- fact: another.json#z.w -->' '```' > "$FIX/howto.md"
$TU --repo "$FIX" >/dev/null 2>&1 && ok "anchor examples in code formatting do not fail-loud" || no "anchor examples in code must not fail-loud"
rm -f "$FIX/howto.md"; $TU --repo "$FIX" >/dev/null 2>&1

# T6 — externality detection (machine-local leak). NB: --externalities now GATES (exit 1 on a leak),
# so assert on captured OUTPUT, not the pipeline exit (pipefail would otherwise mask the grep).
printf '%s\n' 'path: /home/someuser/x' > "$FIX/leak.md"
out="$($TU --repo "$FIX" --externalities 2>/dev/null)"; echo "$out" | grep -q '\[high\]' && ok "--externalities flags a /home leak" || no "--externalities flags a leak"
rm -f "$FIX/leak.md"
out="$($TU --repo "$FIX" --externalities 2>/dev/null)"; echo "$out" | grep -q ': 0 (0 high)' && ok "--externalities clean otherwise" || no "--externalities clean otherwise"

# T7 — zone/policy gate clean
$TU --repo "$FIX" --policy 2>/dev/null | grep -q 'policy violations: 0' && ok "--policy reports 0 violations" || no "--policy reports 0 violations"

# T8 — the deterministic true-up loop reaches GREEN on a clean target
$TU --repo "$FIX" run --since HEAD 2>/dev/null | grep -q 'GREEN' && ok "run --since reaches GREEN on a clean repo" || no "run reaches GREEN"

# T9 — HIGH-1: --policy / --externalities are GATES (exit nonzero on violations), with --report opt-out
printf '%s\n' 'see /home/bob/secret/x' > "$FIX/leak2.md"
$TU --repo "$FIX" --policy >/dev/null 2>&1; rc=$?;        [ "$rc" -ne 0 ] && ok "HIGH-1: --policy EXITS NONZERO on a violation" || no "HIGH-1: --policy must gate"
$TU --repo "$FIX" --externalities >/dev/null 2>&1; rc=$?; [ "$rc" -ne 0 ] && ok "HIGH-1: --externalities EXITS NONZERO on a leak" || no "HIGH-1: --externalities must gate"
$TU --repo "$FIX" --policy --report >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "HIGH-1: --policy --report stays exit 0 (report-only)" || no "HIGH-1: --report must exit 0"
rm -f "$FIX/leak2.md"; $TU --repo "$FIX" >/dev/null 2>&1
$TU --repo "$FIX" --policy >/dev/null 2>&1; rc=$?;        [ "$rc" -eq 0 ] && ok "HIGH-1: --policy exits 0 when clean" || no "--policy must exit 0 when clean"

# T10 — HIGH-2: a machine-local path shown inside CODE formatting (docs explaining a rule) is NOT a leak
printf '%s\n' '# privacy policy' 'We reject paths like `/home/alice/private/` in values.' '```' 'example: /home/bob/scratch/' '```' > "$FIX/privacy.md"
$TU --repo "$FIX" --externalities >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "HIGH-2: /home in inline+fenced code is not flagged (stripCode in detectors)" || no "HIGH-2: code-span paths must not be flagged"
rm -f "$FIX/privacy.md"; $TU --repo "$FIX" >/dev/null 2>&1

# T11 — suppression directives mute a legit path-example in prose; scope is per-line
printf '%s\n' '# notes' 'avoid /home/eve/x/ here <!-- true-up:ignore-line -->' '<!-- true-up:ignore-next no-machine-local-paths -->' 'and /home/eve/y/ here' > "$FIX/sup.md"
$TU --repo "$FIX" --externalities >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "suppression: ignore-line + ignore-next mute path findings" || no "suppression directives must mute findings"
printf '%s\n' '# notes' 'and /home/eve/z/ here (no directive)' > "$FIX/sup.md"
$TU --repo "$FIX" --externalities >/dev/null 2>&1; rc=$?; [ "$rc" -ne 0 ] && ok "suppression is per-line (an unmarked leak still flags)" || no "unmarked leak must still flag"
rm -f "$FIX/sup.md"; $TU --repo "$FIX" >/dev/null 2>&1

# T12 — MED: --impact --since <bad ref> is exit 2, NOT a silent "0 dependents" exit 0
$TU --repo "$FIX" --impact --since deadbeefb0gusref >/dev/null 2>&1; rc=$?; [ "$rc" -eq 2 ] && ok "MED: --impact --since <bad ref> exits 2 (distinct from 0 impact)" || no "bad --since ref must exit 2"

# T13 — HIGH-4: --help and unknown args WRITE NOTHING into the target repo
H="$(mktemp -d)"; git -C "$H" init -q
$TU --repo "$H" --help >/dev/null 2>&1; rc=$?;  { [ "$rc" -eq 0 ] && [ ! -e "$H/.true-up" ]; } && ok "HIGH-4: --help exits 0 and writes nothing" || no "HIGH-4: --help must not write"
$TU --repo "$H" --bogus >/dev/null 2>&1; rc=$?; { [ "$rc" -eq 2 ] && [ ! -e "$H/.true-up" ]; } && ok "HIGH-4: unknown command exits 2 and writes nothing" || no "HIGH-4: unknown arg must exit 2, no write"
$TU --repo "$H" >/dev/null 2>&1; [ -e "$H/.true-up/depgraph.json" ] && ok "build (no args) still writes the graph" || no "build must write"

# T14 — HIGH-3: --check --committed is the real drift gate (untracked / stale committed blob both fail)
C="$(mktemp -d)"; git -C "$C" init -q
printf '%s\n' '{ "items": [ { "id": "a", "v": 1 } ] }' > "$C/data.json"
printf '%s\n' '{ "facts": { "data.json": [["items","id"]] }, "zones": [ {"path":"","visibility":"public","audience":"world","intent":"public","rules":["no-machine-local-paths"]} ], "seed": [] }' > "$C/.true-up.json"
git -C "$C" add -A && git -C "$C" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$C" >/dev/null 2>&1
$TU --repo "$C" --check --committed >/dev/null 2>&1; rc=$?; [ "$rc" -ne 0 ] && ok "HIGH-3: --check --committed FAILS when the graph is untracked" || no "HIGH-3: untracked graph must fail --committed"
$TU --repo "$C" --check >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "HIGH-3: plain --check (working-tree freshness) passes on a fresh on-disk graph" || no "HIGH-3: worktree --check must pass when fresh"
git -C "$C" add .true-up/depgraph.json && git -C "$C" -c user.email=t@t -c user.name=t commit -qm graph
$TU --repo "$C" --check --committed >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "HIGH-3: --check --committed passes when the committed graph is fresh" || no "HIGH-3: fresh committed graph must pass"
printf '%s\n' '{ "items": [ { "id": "a", "v": 999 } ] }' > "$C/data.json"
$TU --repo "$C" --check --committed >/dev/null 2>&1; rc=$?; [ "$rc" -ne 0 ] && ok "HIGH-3: --check --committed catches a STALE committed blob" || no "HIGH-3: stale committed graph must fail"

# T15 — LIMITATION fix: a declared (seed) edge to a code file (e.g. .py) is not silently dropped
P="$(mktemp -d)"; git -C "$P" init -q
printf '%s\n' 'def f(): pass' > "$P/registry.py"
printf '%s\n' '# doc' 'derived from the registry' > "$P/doc.md"
printf '%s\n' '{ "zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}], "seed":[ {"from":"doc.md","to":"registry.py","kind":"derives-facts-from"} ] }' > "$P/.true-up.json"
git -C "$P" add -A && git -C "$P" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$P" >/dev/null 2>&1
grep -q 'registry.py' "$P/.true-up/depgraph.json" && ok "seed edge to a .py creates a node (edge not dropped)" || no "seed edge to code file must resolve"
$TU --repo "$P" --impact registry.py 2>/dev/null | grep -q 'doc.md' && ok "--impact on a code source shows its dependent" || no "--impact .py must show dependent"

# T16 — init scaffolds a config and refuses to clobber one
E="$(mktemp -d)"; git -C "$E" init -q
$TU --repo "$E" init >/dev/null 2>&1; rc=$?; { [ "$rc" -eq 0 ] && [ -f "$E/.true-up.json" ]; } && ok "init scaffolds .true-up.json" || no "init must write .true-up.json"
$TU --repo "$E" init >/dev/null 2>&1; rc=$?; [ "$rc" -ne 0 ] && ok "init refuses to overwrite an existing config" || no "init must not overwrite"

# T17 — empty-graph NOTICE: distinguish "nothing changed" from "you declared nothing to track"
out="$($TU --repo "$E" 2>&1)"
echo "$out" | grep -q 'NOTICE' && ok "empty-graph NOTICE warns when nothing is declared (inert graph)" || no "must warn on an inert graph"

# T18 — HIGH-3 hygiene: --check --committed on an untracked graph must not leak raw git "fatal:" noise
# (P's graph was built in T15 but never committed -> untracked). stderr only:
err="$($TU --repo "$P" --check --committed 2>&1 1>/dev/null)"
echo "$err" | grep -q 'fatal:' && no "blob() must suppress git fatal: noise on untracked graph" || ok "--check --committed (untracked) emits no raw git fatal: noise"

# T19 — cross-repo hygiene: a stale-graph regenerate hint must be generic, not an ugly ../.. engine path
# (C's on-disk graph is stale after T14 changed data.json). stderr only:
err="$($TU --repo "$C" --check 2>&1 1>/dev/null)"
echo "$err" | grep -q '\.\./\.\.' && no "cross-repo regenerate hint leaks a ../.. path" || ok "cross-repo regenerate hint is generic (no ../.. path)"

# T20 — --verify-scope: the deterministic anti-code-golf gate (empirically: unguarded LLMs hit the decoy 3/3)
V="$(mktemp -d)"; git -C "$V" init -q
printf '%s\n' '{ "items": [ { "id": "a", "v": 1 } ] }' > "$V/data.json"
printf '%s\n' '# dep' 'a is 1 <!-- fact: data.json#items.a -->' > "$V/dep.md"
printf '%s\n' '# leaf' 'a is mentioned here but is not anchored to any fact.' > "$V/leaf.md"
printf '%s\n' '{ "facts": { "data.json": [["items","id"]] }, "zones": [ {"path":"","visibility":"public","audience":"world","intent":"public","rules":[]} ], "seed": [] }' > "$V/.true-up.json"
node "$TU" --repo "$V" >/dev/null 2>&1
git -C "$V" add -A && git -C "$V" -c user.email=t@t -c user.name=t commit -qm good
# in-scope maintenance: move the fact + update ONLY its anchored dependent
printf '%s\n' '{ "items": [ { "id": "a", "v": 2 } ] }' > "$V/data.json"
printf '%s\n' '# dep' 'a is 2 <!-- fact: data.json#items.a -->' > "$V/dep.md"
$TU --repo "$V" --verify-scope --since HEAD >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "--verify-scope PASSES when edits stay in the blast radius" || no "--verify-scope must pass in-scope edits"
# now ALSO edit the unanchored leaf (the decoy) -> out of scope -> FAIL, naming it
printf '%s\n' '# leaf' 'a is 2 now (an out-of-scope tidy).' > "$V/leaf.md"
out="$($TU --repo "$V" --verify-scope --since HEAD 2>&1)"; rc=$?
{ [ "$rc" -ne 0 ] && echo "$out" | grep -q 'leaf.md'; } && ok "--verify-scope FAILS on an out-of-blast-radius (code-golf) edit, naming it" || no "--verify-scope must catch out-of-scope edits"

# T21 — must-be-ciphertext is STRUCTURE-AWARE: a plaintext file that merely MENTIONS sops must FAIL
M="$(mktemp -d)"; git -C "$M" init -q; mkdir -p "$M/private"
printf '%s\n' '# notes' 'we use sops to encrypt this directory.' > "$M/private/notes.md"
printf '%s\n' '{ "zones": [ {"path":"private/","visibility":"private","audience":"team","intent":"enc","rules":["must-be-ciphertext"]}, {"path":"","visibility":"public","audience":"world","intent":"pub","rules":[]} ] }' > "$M/.true-up.json"
git -C "$M" add -A && git -C "$M" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$M" --policy --report 2>&1 | grep -q 'must-be-ciphertext' && ok "must-be-ciphertext FLAGS plaintext that merely mentions 'sops'" || no "must-be-ciphertext must reject plaintext mentioning sops"
printf '%s\n' 'data: ENC[AES256_GCM,data:Zm9v,iv:YmFy,tag:YmF6,type:str]' 'sops:' '    mac: ENC[AES256_GCM,data:abc,type:str]' > "$M/private/notes.md"
$TU --repo "$M" --policy --report 2>&1 | grep -q 'must-be-ciphertext' && no "real ENC[…] ciphertext must pass must-be-ciphertext" || ok "real ENC[…] ciphertext passes must-be-ciphertext"

# T22 — ergonomics: --version + capabilities (the machine-readable contract, Axiom 9)
$TU --repo "$FIX" --version 2>&1 | grep -qE '[0-9]+\.[0-9]+' && ok "--version prints a version" || no "--version must print a version"
$TU --repo "$FIX" capabilities 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.exit_codes&&d.commands&&d.version?0:1)' && ok "capabilities is valid JSON with version/commands/exit_codes" || no "capabilities must be a valid JSON contract"

# T23 — ergonomics: --json on read-side gates is pure, valid JSON on stdout (Axiom 8/4)
$TU --repo "$FIX" --policy --json --report 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(Array.isArray(d.violations)&&typeof d.count==="number"?0:1)' && ok "--policy --json is valid structured JSON" || no "--policy --json must be valid JSON"
$TU --repo "$FIX" --externalities --json --report 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(Array.isArray(d.hits)?0:1)' && ok "--externalities --json is valid structured JSON" || no "--externalities --json must be valid JSON"
$TU --repo "$FIX" --impact --json 'data.json#items.a' 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(Array.isArray(d.advisory)?0:1)' && ok "--impact --json is valid structured JSON" || no "--impact --json must be valid JSON"

# T24 — ergonomics: a mistyped command gets a 'did you mean' suggestion (Axiom 7 intent inference)
err="$($TU --repo "$FIX" --externalites 2>&1)"; rc=$?
{ [ "$rc" -eq 2 ] && echo "$err" | grep -q 'did you mean: --externalities'; } && ok "did-you-mean suggests the nearest command on a typo" || no "must suggest nearest command on a typo"

# T25 — Tier 1: language-agnostic SPAN ANCHORS make CODE a content-hashed source-of-truth.
# A paired comment-token region (any language; here Python — the .py-is-inert gap) becomes a
# fact node; a doc that anchors to it gets an advisory derives-facts-from edge.
S="$(mktemp -d)"; git -C "$S" init -q
printf '%s\n' '# true-up:anchor id=parse_config' 'def parse_config(path):' '    return load(path)' '# true-up:end id=parse_config' > "$S/parser.py"
printf '%s\n' '# API' 'parse_config loads the config. <!-- fact: parser.py#parse_config -->' > "$S/api.md"
printf '%s\n' '{ "zones": [ {"path":"","visibility":"public","audience":"world","intent":"public","rules":[]} ], "seed": [] }' > "$S/.true-up.json"
git -C "$S" add -A && git -C "$S" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$S" >/dev/null 2>&1 && ok "Tier1: build succeeds with a code span anchor + doc anchor" || no "Tier1: build must succeed with a code span anchor"
$TU --repo "$S" --impact 'parser.py#parse_config' 2>/dev/null | grep -q 'api.md' && ok "Tier1: a doc derives-facts-from a CODE span (language-agnostic)" || no "Tier1: code span fact-edge must resolve"

# T25b — a malformed span is harmless ON ITS OWN (so files can document the token without self-tripping),
# but a doc that ANCHORS to a span which never formed a complete pair FAILS LOUD (unresolved-anchor backstop).
printf '%s\n' '# true-up:anchor id=orphan' 'def f(): return 1' > "$S/lonely.py"
$TU --repo "$S" >/dev/null 2>&1 && ok "Tier1: a lone unclosed span nobody depends on is harmless (no self-trip)" || no "Tier1: lone unclosed span must not fail the build"
printf '%s\n' 'see <!-- fact: lonely.py#orphan -->' > "$S/needsit.md"
out="$($TU --repo "$S" 2>&1)"; rc=$?
{ [ "$rc" -ne 0 ] && echo "$out" | grep -q 'lonely.py#orphan'; } && ok "Tier1: a doc anchoring to a non-formed span FAILS LOUD (names it)" || no "Tier1: anchor to a missing span must fail-loud"
rm -f "$S/lonely.py" "$S/needsit.md"; $TU --repo "$S" >/dev/null 2>&1

# T25c — INCIDENT guard (mirror of T5b): span-anchor EXAMPLES inside markdown code formatting
# (a doc explaining THIS feature) must NOT be parsed as live spans.
printf '%s\n' '# how-to' 'Bracket a region:' '```' '# true-up:anchor id=demo' 'code here' '# true-up:end id=demo' '```' > "$S/howto.md"
$TU --repo "$S" >/dev/null 2>&1 && ok "Tier1: span examples in markdown code fences do not fail-loud" || no "Tier1: fenced span examples must not fail-loud"
grep -q 'fact:howto.md#demo' "$S/.true-up/depgraph.json" && no "Tier1: a fenced span example must NOT create a live fact node" || ok "Tier1: fenced span example is inert (no spurious fact node)"
rm -f "$S/howto.md"; $TU --repo "$S" >/dev/null 2>&1

# T25d — EARLY-CUTOFF for span facts: editing a span's BODY stales its anchored doc via --since;
# editing the file OUTSIDE the span does NOT (the whole point of fact-granular hashing).
git -C "$S" checkout -- parser.py 2>/dev/null
printf '%s\n' '# true-up:anchor id=parse_config' 'def parse_config(path):' '    return load2(path)  # body changed' '# true-up:end id=parse_config' > "$S/parser.py"
$TU --repo "$S" >/dev/null 2>&1
$TU --repo "$S" --impact --since HEAD 2>/dev/null | grep -q 'api.md' && ok "Tier1: editing a span BODY stales its anchored doc (--since early-cutoff)" || no "Tier1: span-body change must stale the doc via --since"
git -C "$S" checkout -- parser.py 2>/dev/null
printf '%s\n' '# true-up:anchor id=parse_config' 'def parse_config(path):' '    return load(path)' '# true-up:end id=parse_config' '' 'def unrelated(): pass  # outside the span' > "$S/parser.py"
$TU --repo "$S" >/dev/null 2>&1
$TU --repo "$S" --impact --since HEAD 2>/dev/null | grep -q 'api.md' && no "Tier1: an edit OUTSIDE the span must NOT stale the doc (early-cutoff)" || ok "Tier1: edit outside the span does not stale the doc (early-cutoff)"
git -C "$S" checkout -- parser.py 2>/dev/null; $TU --repo "$S" >/dev/null 2>&1

# T25e — a repo whose ONLY facts come from span anchors (no config "facts") is NOT inert: it has
# real edges, so build must NOT cry INERT (the dogfood bug: `inert` ignored span facts).
out="$($TU --repo "$S" 2>&1)"
echo "$out" | grep -q 'INERT' && no "Tier1: a span-anchored repo must NOT be reported INERT" || ok "Tier1: span-anchored repo is not INERT (has real edges)"

# T26 — Tier 2: tree-sitter SYMBOL extraction (config-driven "symbols": true) auto-lifts code
# definitions to fact nodes with NO manual markers; a doc anchors to a symbol by name. (Opt-in,
# optional dependency; the zero-dep core never loads tree-sitter.)
Y="$(mktemp -d)"; git -C "$Y" init -q
printf '%s\n' 'import os' '' 'def parse_config(path):' '    return load(path)' '' 'class Cfg:' '    def get(self):' '        return 1' > "$Y/app.py"
printf '%s\n' '# Guide' 'parse_config reads the config. <!-- fact: app.py#parse_config -->' > "$Y/guide.md"
printf '%s\n' '{ "symbols": true, "zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}], "seed":[] }' > "$Y/.true-up.json"
git -C "$Y" add -A && git -C "$Y" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$Y" >/dev/null 2>&1 && ok "Tier2: build succeeds with symbols enabled + a symbol anchor" || no "Tier2: symbols build must succeed"
$TU --repo "$Y" --impact 'app.py#parse_config' 2>/dev/null | grep -q 'guide.md' && ok "Tier2: a doc derives-facts-from an auto-extracted CODE SYMBOL (tree-sitter)" || no "Tier2: symbol fact-edge must resolve"

# T27 — Tier 2 EARLY-CUTOFF: editing a SYMBOL's body stales docs anchored to THAT symbol via --since;
# editing a different symbol does not (symbol-granular hashing).
git -C "$Y" add -A && git -C "$Y" -c user.email=t@t -c user.name=t commit -qm base
printf '%s\n' 'import os' '' 'def parse_config(path):' '    return load2(path)  # changed' '' 'class Cfg:' '    def get(self):' '        return 1' > "$Y/app.py"
$TU --repo "$Y" >/dev/null 2>&1
$TU --repo "$Y" --impact --since HEAD 2>/dev/null | grep -q 'guide.md' && ok "Tier2: editing a symbol BODY stales its anchored doc (--since)" || no "Tier2: symbol body change must stale the doc"
git -C "$Y" checkout -- app.py 2>/dev/null
printf '%s\n' 'import os' '' 'def parse_config(path):' '    return load(path)' '' 'class Cfg:' '    def get(self):' '        return 1' '' 'def helper():' '    return 2' > "$Y/app.py"
$TU --repo "$Y" >/dev/null 2>&1
$TU --repo "$Y" --impact --since HEAD 2>/dev/null | grep -q 'guide.md' && no "Tier2: editing a DIFFERENT symbol must NOT stale the doc (early-cutoff)" || ok "Tier2: edit of an unrelated symbol does not stale the doc"
git -C "$Y" checkout -- app.py 2>/dev/null; $TU --repo "$Y" >/dev/null 2>&1

# T28 — Tier 2 is genuinely multi-language: a C++ function's name lives in a DECLARATOR (not a name
# field), exercising the harder extraction path (geometry-central, the top dogfood gap, is C++).
Z="$(mktemp -d)"; git -C "$Z" init -q
printf '%s\n' '#include <string>' '' 'int parse_input(const char* p) {' '    return 0;' '}' > "$Z/api.cpp"
printf '%s\n' '# Docs' 'parse_input returns a status code. <!-- fact: api.cpp#parse_input -->' > "$Z/docs.md"
printf '%s\n' '{ "symbols": true, "zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}], "seed":[] }' > "$Z/.true-up.json"
git -C "$Z" add -A && git -C "$Z" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$Z" >/dev/null 2>&1
$TU --repo "$Z" --impact 'api.cpp#parse_input' 2>/dev/null | grep -q 'docs.md' && ok "Tier2: C++ function symbol extracted via declarator + anchored (multi-language)" || no "Tier2: C++ symbol must resolve"

# T29 — P0 (ergonomics): per-command flag validation. A typo'd flag must be REJECTED (exit 2 +
# did-you-mean), never silently dropped. The worst case: --comitted downgrades the committed drift
# gate to the worktree check (exit 1→0) — a one-char typo defeating a CI gate. (verified live)
G="$(mktemp -d)"; git -C "$G" init -q
printf '%s\n' '{ "items": [ { "id": "a", "v": 1 } ] }' > "$G/data.json"
printf '%s\n' '{ "facts": { "data.json": [["items","id"]] }, "zones": [ {"path":"","visibility":"public","audience":"world","intent":"public","rules":[]} ], "seed": [] }' > "$G/.true-up.json"
git -C "$G" add -A && git -C "$G" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$G" >/dev/null 2>&1
git -C "$G" add .true-up/depgraph.json && git -C "$G" -c user.email=t@t -c user.name=t commit -qm graph
printf '%s\n' '{ "items": [ { "id": "a", "v": 999 } ] }' > "$G/data.json"
$TU --repo "$G" >/dev/null 2>&1   # worktree graph fresh, committed blob now stale
out="$($TU --repo "$G" --check --comitted 2>&1)"; rc=$?
{ [ "$rc" -eq 2 ] && echo "$out" | grep -q 'did you mean: --committed'; } && ok "P0: --comitted typo is REJECTED (exit 2 + did-you-mean), not a silent gate downgrade" || no "P0: --comitted must not silently downgrade the committed gate"
$TU --repo "$G" --impact --snice HEAD~1 >/dev/null 2>&1; rc=$?; [ "$rc" -eq 2 ] && ok "P0: --impact --snice (typo) exits 2, not a bogus positional '0 dependents'" || no "P0: --impact typo flag must exit 2"
$TU --repo "$G" --check --committed >/dev/null 2>&1; rc=$?; [ "$rc" -ne 2 ] && ok "P0: legit --committed still accepted (validator does not over-reject)" || no "P0: validator must not reject legit flags"

# T30 — P1 (ergonomics): the rebuild hint must be runnable. Against true-up's OWN repo, relative(self)
# is 'lib/engine.mjs' (no '..'), which is not executable — copy-paste → exit 126. Hint must say true-up.
err="$(cd "$HERE" && node bin/true-up bogus 2>&1)"
echo "$err" | grep -qE 'engine\.mjs|^lib/' && no "P1: self error-hint must not name the non-runnable engine path" || ok "P1: in-repo error hint is runnable (not lib/engine.mjs)"

# T31 — P0 (ergonomics): run --json and --version --json must emit JSON (the contract capabilities
# advertises). run is the mega-command agents script with | jq; both emitted human text. (verified)
$TU --repo "$FIX" run --since HEAD --json 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(typeof d.green==="boolean"&&d.verify?0:1)' && ok "P0: run --json is valid structured JSON" || no "P0: run --json must be valid JSON"
$TU --repo "$FIX" --version --json 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.version?0:1)' && ok "P0: --version --json is valid JSON" || no "P0: --version --json must be valid JSON"

# T32 — adoption: `true-up hooks` wires a per-repo gate. --install writes executable pre-commit +
# pre-push hooks running the leak/zone gate; idempotent; the installed hook actually BLOCKS a leak;
# --ci prints a version-pinned snippet; --uninstall removes only the managed hooks.
K="$(mktemp -d)"; git -C "$K" init -q
printf '%s' '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":["no-machine-local-paths"]}]}' > "$K/.true-up.json"
git -C "$K" add -A && git -C "$K" -c user.email=t@t -c user.name=t commit -qm init
$TU --repo "$K" hooks --install >/dev/null 2>&1
{ [ -x "$K/.git/hooks/pre-commit" ] && [ -x "$K/.git/hooks/pre-push" ]; } && ok "hooks: --install writes executable pre-commit + pre-push" || no "hooks --install must write executable hooks"
{ grep -q 'true-up --policy' "$K/.git/hooks/pre-commit" && grep -q 'true-up --externalities' "$K/.git/hooks/pre-commit"; } && ok "hooks: the gate runs --policy + --externalities" || no "hook must run the gates"
$TU --repo "$K" hooks --install >/dev/null 2>&1
[ "$(grep -c 'managed-by: true-up-hooks' "$K/.git/hooks/pre-commit")" -eq 1 ] && ok "hooks: --install is idempotent (no stacking)" || no "hooks --install must be idempotent"
mkdir -p "$K/shim"; printf '%s\n' '#!/bin/sh' "exec node \"$HERE/bin/true-up\" \"\$@\"" > "$K/shim/true-up"; chmod +x "$K/shim/true-up"
printf '%s\n' 'see /home/somebody/secret/x' > "$K/leak.md"; git -C "$K" add leak.md
if PATH="$K/shim:$PATH" git -C "$K" -c user.email=t@t -c user.name=t commit -qm leak >/dev/null 2>&1; then no "hooks: pre-commit must BLOCK a leak commit"; else ok "hooks: the installed pre-commit BLOCKS a commit that adds a machine-local-path leak"; fi
git -C "$K" reset -q HEAD leak.md 2>/dev/null; rm -f "$K/leak.md"
$TU --repo "$K" hooks --ci 2>/dev/null | grep -q 'npx true-up@' && ok "hooks: --ci prints a version-pinned CI snippet" || no "hooks --ci must print a CI snippet"
$TU --repo "$K" hooks --uninstall >/dev/null 2>&1
{ [ ! -e "$K/.git/hooks/pre-commit" ] && [ ! -e "$K/.git/hooks/pre-push" ]; } && ok "hooks: --uninstall removes the managed hooks" || no "hooks --uninstall must remove them"

# T33 — gate: one CI stage = --check + --policy + --externalities; exit code is authoritative (a runner
# keys on it, not stdout). Exits 0 when clean, nonzero when ANY sub-check fails; --json per-check status.
$TU --repo "$FIX" >/dev/null 2>&1
$TU --repo "$FIX" gate >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "gate: exits 0 on a clean repo (check+policy+externalities)" || no "gate must pass when clean"
$TU --repo "$FIX" gate --json 2>/dev/null | node -e 'const d=JSON.parse(require("fs").readFileSync(0,"utf8"));process.exit(d.ok===true&&d.checks&&typeof d.checks.policy==="boolean"?0:1)' && ok "gate --json reports per-check status" || no "gate --json must be structured"
printf '%s\n' 'leak /home/someone/y/z' > "$FIX/gateleak.md"
$TU --repo "$FIX" gate >/dev/null 2>&1; rc=$?; [ "$rc" -ne 0 ] && ok "gate: EXITS NONZERO when a sub-check fails (a leak)" || no "gate must fail on any sub-check failure"
rm -f "$FIX/gateleak.md"; $TU --repo "$FIX" >/dev/null 2>&1

# T34 — strictSpans (consumer ask): "strictSpans": true makes a malformed span anchor FATAL so a CI
# gate can't be fooled by a silently-dropped span; default stays lenient (no self-trip on doc'd tokens).
printf '%s' '{"strictSpans":true,"zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}]}' > "$K/.true-up.json"
printf '%s\n' '# true-up:anchor id=dup' 'a' '# true-up:end id=dup' '# true-up:anchor id=dup' 'b' '# true-up:end id=dup' > "$K/dup.py"
out="$($TU --repo "$K" 2>&1)"; rc=$?
{ [ "$rc" -ne 0 ] && echo "$out" | grep -q 'dup'; } && ok "strictSpans: a malformed span (duplicate id) FAILS the build (names it)" || no "strictSpans must fail on a malformed span"
printf '%s' '{"zones":[{"path":"","visibility":"public","audience":"world","intent":"public","rules":[]}]}' > "$K/.true-up.json"
$TU --repo "$K" >/dev/null 2>&1; rc=$?; [ "$rc" -eq 0 ] && ok "default (no strictSpans): the same malformed span is lenient (no self-trip)" || no "default must stay lenient on malformed spans"
rm -f "$K/dup.py"

echo
echo "engine tests: ${pass} passed, ${fail} failed"
[ "$fail" = 0 ] || exit 1
