#!/usr/bin/env node
// Build (or --check, or query --impact) the typed dependency graph of this repo.
//
//   node meta/build-depgraph.mjs                       # (re)write meta/depgraph.json
//   node meta/build-depgraph.mjs --check               # exit 1 if depgraph.json is stale
//   node meta/build-depgraph.mjs --impact <path|path#fact>...   # who is made stale
//
// LAYER 2 (detection). A typed, content-hashed, *directed* dependency graph spanning
// code + data + prose, whose edges carry a CAUSAL direction (from = dependent /
// downstream, to = source-of-truth).
//
// Direction never comes from correlation. Only from a causal basis:
//   - generator : a build script's input->output, from the self-describing
//                 "generated by X from Y" markers already in the repo.    (mechanical)
//   - declared  : a steward registry in depgraph.seed.json.              (advisory)
//   - anchored  : an inline marker in the dependent pointing at a FACT
//                 (<!-- fact: <path>#<arrayProp>.<key> -->).             (mechanical, fact-granular)
// Correlation signals (co-change / embeddings) may only PROPOSE undirected
// candidates; they never assign the arrow, so none are emitted here.
//
// Granularity: steward data files are decomposed into per-fact nodes (content-hashed
// individually) so an anchored dependent is only stale when THAT fact's hash moves
// (early-cutoff) — not when any unrelated part of the file changes.
//
// Fail-loud: an anchor whose fact path does not resolve is a hard error (aplumb's
// "stable IDs, fail on mismatch" lesson) — a silently-wrong anchor is worse than none.
//
// Zero-dep node, deterministic output (sorted, no timestamps) so --check is honest.

import { readFileSync, writeFileSync, mkdirSync, lstatSync, readlinkSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, relative } from 'node:path'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'

const here = (p) => resolve(dirname(fileURLToPath(import.meta.url)), p)

// This is the TOOL: it operates on a TARGET repo, not its own directory.
// Target = --repo <path> | $TRUE_UP_REPO | git toplevel of CWD | CWD.
function resolveRoot() {
  const i = process.argv.indexOf('--repo')
  if (i >= 0 && process.argv[i + 1]) return resolve(process.argv[i + 1])
  if (process.env.TRUE_UP_REPO) return resolve(process.env.TRUE_UP_REPO)
  try { return execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim() } catch { return process.cwd() }
}
const ROOT = resolveRoot()

// Per-repo config: <ROOT>/.true-up.json (or true-up.config.json) declares stewards (facts),
// zones, declared edges, and the output path. Everything repo-specific lives here, not in code.
function loadConfig() {
  for (const name of ['.true-up.json', 'true-up.config.json']) {
    try { return JSON.parse(readFileSync(resolve(ROOT, name), 'utf8')) } catch {}
  }
  return {}
}
const CONFIG = loadConfig()
const OUT = resolve(ROOT, CONFIG.out || '.true-up/depgraph.json')
// steward files decomposed into per-fact nodes: path -> [ [arrayProp, keyField] ]  (from config)
const FACTS = CONFIG.facts || {}

const sha256 = (s) => createHash('sha256').update(s).digest('hex').slice(0, 16)
const rel = (abs) => relative(ROOT, abs)

// deep key-sorted stringify so a fact's hash is order-independent
function sortKeys(v) {
  if (Array.isArray(v)) return v.map(sortKeys)
  if (v && typeof v === 'object') {
    const o = {}
    for (const k of Object.keys(v).sort()) o[k] = sortKeys(v[k])
    return o
  }
  return v
}
const stable = (v) => JSON.stringify(sortKeys(v))
// Blank out fenced + inline code so syntax shown in DOCUMENTATION (a doc explaining true-up's own
// <!-- fact: --> / generated-by markers) is never parsed as a live anchor/marker. Preserves line
// count (replaces non-newline chars with spaces) so any line numbers stay accurate.
const stripCode = (s) => s.replace(/```[\s\S]*?```/g, (m) => m.replace(/[^\n]/g, ' ')).replace(/`[^`\n]+`/g, (m) => ' '.repeat(m.length))

// ---- zones / policy ----
function loadZones() {
  // default: one public-default zone so --policy enforces no-machine-local-paths everywhere out of the box
  return CONFIG.zones || [{ path: '', visibility: 'public', audience: 'world', intent: 'public-default', rules: ['no-machine-local-paths'] }]
}
function zoneScore(zpath, path) {
  if (zpath === path) return 1000
  if (zpath.startsWith('**/') && path.endsWith(zpath.slice(2))) return 600 + zpath.length
  if (zpath.startsWith('*') && path.endsWith(zpath.slice(1))) return 500 + zpath.length
  if (zpath.endsWith('/') && path.startsWith(zpath)) return 100 + zpath.length
  if (zpath === '' || zpath === '/') return 1
  return -1
}
function zoneOf(path, zones) {
  let best = null
  let bestS = 0
  for (const z of zones) { const s = zoneScore(z.path, path); if (s > bestS) { bestS = s; best = z } }
  return best
}
// machine-local path leaks (canonical ~/.claude etc. allowlisted)
const EXT_PATS = [
  { re: /\/home\/[a-z][\w.\-]*\//gi, sev: 'high' },
  { re: /\/Users\/[A-Za-z][\w.\-]*\//g, sev: 'high' },
  { re: /(?<![$\w])~\/[\w./\-]+/g, sev: 'med' },
]
const EXT_ALLOW = [/^~\/\.(claude|config|cache)\b/]
function machineLocalHits(content) {
  const hits = []
  content.split('\n').forEach((line, i) => {
    for (const p of EXT_PATS) {
      p.re.lastIndex = 0
      let m
      while ((m = p.re.exec(line))) { if (EXT_ALLOW.some((a) => a.test(m[0]))) continue; hits.push({ line: i + 1, sev: p.sev, match: m[0] }) }
    }
  })
  return hits
}

// Private OPERATIONAL/AUTH mechanics that must never appear in a PUBLIC file. This is
// the `share-method-not-operator` advisory PROMOTED to a mechanical rule for the
// concrete tokens that have leaked or are unambiguously operator/auth detail. Naming a
// provider as a sanitized conclusion (a "subscription bridge", a model slug) is allowed
// and intentionally NOT matched; its AUTH MECHANICS — credential file paths, private
// adapter class names, raw backend endpoints — are what leak. Add a token the moment a
// new class of operational detail is found in a public file (harness rule: a leak that
// happened once becomes a lint that can't happen again).
//
// The banned literals are ASSEMBLED FROM FRAGMENTS so this definition never contains a
// contiguous banned token — the rule polices itself without self-tripping (same spirit
// as the escaped machine-local regexes above). Reword comments/docs, never inline a
// literal, when extending this list.
const _leak = (s) => new RegExp(s, 'i')
const PRIVATE_LEAK_PATS = [
  _leak('auth' + '\\.' + 'json'),                        // a credential JSON file
  _leak('\\.cod' + 'ex/auth|\\.pi/' + 'agent'),          // agent-CLI credential directories
  _leak('back' + 'end-api|chatgpt\\.com/back' + 'end'),  // raw subscription backend endpoint
  new RegExp('Codex' + 'SubscriptionLM'),                // a private adapter class name
]
function privateLeakHits(content) {
  const hits = []
  content.split('\n').forEach((line, i) => {
    for (const re of PRIVATE_LEAK_PATS) {
      const m = re.exec(line)
      if (m) hits.push({ line: i + 1, match: m[0] })
    }
  })
  return hits
}

// per-fact hashes for a steward file -> { factId: hash }
function extractFacts(path, content) {
  const out = {}
  const spec = FACTS[path]
  if (!spec) return out
  let data
  try { data = JSON.parse(content) } catch { return out }
  for (const [arrProp, keyField] of spec) {
    const arr = data[arrProp]
    if (!Array.isArray(arr)) continue
    for (const item of arr) {
      const key = item && item[keyField]
      if (key == null) continue
      out[`fact:${path}#${arrProp}.${key}`] = sha256(stable(item))
    }
  }
  return out
}

function listFiles() {
  const git = (args) => {
    try { return execFileSync('git', ['-C', ROOT, ...args], { encoding: 'utf8' }).split('\n').filter(Boolean) }
    catch { return [] }
  }
  const all = [...new Set([...git(['ls-files']), ...git(['ls-files', '--others', '--exclude-standard'])])]
  const KEEP = /\.(md|json|mjs|js)$/
  const SKIP = /^(private\/|node_modules\/|\.git\/|\.jj\/|\.true-up\/)|^\.true-up\.json$|^true-up\.config\.json$|depgraph\.(json|seed\.json)$/
  return all.filter((p) => KEEP.test(p) && !SKIP.test(p)).sort()
}

function classify(path, content) {
  if (/\.(mjs|js)$/.test(path)) return { kind: 'code', role: 'none' }
  if (path.endsWith('.json')) {
    if (FACTS[path]) return { kind: 'data', role: 'steward' }
    return { kind: 'data', role: 'none' }
  }
  if (/^<!--\s*generated by /m.test(content.slice(0, 400))) return { kind: 'generated', role: 'guard' }
  if (path.endsWith('SKILL.md')) return { kind: 'prose', role: 'writer', audience: 'external-agents' }
  if (path === 'README.md' || /\/README\.md$/.test(path)) return { kind: 'prose', role: 'writer', audience: 'users' }
  if (path === 'AGENTS.md') return { kind: 'prose', role: 'writer', audience: 'maintainers' }
  return { kind: 'prose', role: 'writer', audience: 'mixed' }
}

function generatorSource(genRel) {
  try {
    const m = readFileSync(resolve(ROOT, genRel), 'utf8').match(/here\(['"]\.\/([\w.\-]+\.json)['"]\)/)
    if (m) return 'meta/' + m[1]
  } catch {}
  return null
}

function mkEdge(from, to, kind, directionBasis, propagation, granularity, via) {
  return { from, to, kind, directionBasis, propagation, granularity, ...(via ? { via } : {}) }
}

function build() {
  const files = listFiles()
  const nodes = {}
  const edges = []
  const contents = {}
  const anchorErrors = []
  const symlinks = []

  for (const path of files) {
    const abs = resolve(ROOT, path)
    let st
    try { st = lstatSync(abs) } catch { continue }
    if (st.isSymbolicLink()) {
      // a symlink is an ALIAS of its target (e.g. CLAUDE.md -> AGENTS.md): same bytes,
      // one canonical source. Do NOT read the followed content as an independent node.
      let targetRel = null
      try { targetRel = rel(resolve(dirname(abs), readlinkSync(abs))) } catch {}
      nodes['file:' + path] = { kind: 'symlink', role: 'alias', ...(targetRel ? { symlinkTo: targetRel } : {}), hash: sha256('symlink->' + (targetRel || '?')) }
      if (targetRel) symlinks.push({ from: path, to: targetRel })
      continue
    }
    let content
    try { content = readFileSync(abs, 'utf8') } catch { continue }
    contents[path] = content
    const m = classify(path, content)
    nodes['file:' + path] = { kind: m.kind, role: m.role, ...(m.audience ? { audience: m.audience } : {}), hash: sha256(content) }
    // decompose steward data files into per-fact nodes
    for (const [factId, h] of Object.entries(extractFacts(path, content))) {
      nodes[factId] = { kind: 'fact', role: 'steward-fact', hash: h }
    }
  }

  for (const path of files) {
    const content = contents[path]
    if (!content) continue
    if (/\.(mjs|js)$/.test(path)) continue // code files carry marker strings as literals
    const scan = stripCode(content) // markers/anchors inside code formatting are docs, not live
    // whole-file generated marker
    const whole = scan.match(/<!--\s*generated by\s+([^\s)]+)(?:\s+from\s+([^\s)]+))?/)
    if (whole && /^<!--\s*generated by /m.test(scan.slice(0, 400))) {
      const source = whole[2] || generatorSource(whole[1])
      if (source && nodes['file:' + source]) edges.push(mkEdge('file:' + path, 'file:' + source, 'generated-from', 'generator', 'mechanical', 'file', whole[1]))
    }
    // generated BLOCK marker
    const blk = scan.match(/<!--\s*([A-Z]+):START\s*\(generated by\s+([^\s)]+)[^]*?-->([^]*?)<!--\s*\1:END\s*-->/)
    if (blk) {
      const [, tag, gen, body] = blk
      const source = generatorSource(gen)
      nodes[`block:${path}#${tag}`] = { kind: 'generated', role: 'guard', hash: sha256(body) }
      if (source && nodes['file:' + source]) edges.push(mkEdge(`block:${path}#${tag}`, 'file:' + source, 'generated-from', 'generator', 'mechanical', 'span', gen))
    }
    // anchored fact markers -> directed, fact-granular, mechanical (FAIL LOUD if unresolved)
    for (const m of scan.matchAll(/<!--\s*fact:\s*([\w./\-]+#[\w.\-]+)\s*-->/g)) {
      const factId = 'fact:' + m[1]
      // anchored prose dep: fact-GRANULAR (fires only on that fact) but ADVISORY (a human/LLM
      // rewrites the prose) — only generated-from is mechanical/regenerable.
      if (nodes[factId]) edges.push(mkEdge('file:' + path, factId, 'derives-facts-from', 'anchored', 'advisory', 'fact', null))
      else anchorErrors.push({ file: path, anchor: m[1] })
    }
  }

  // declared edges (file granularity, advisory) from the steward registry
  const seed = { edges: CONFIG.seed || [] }
  for (const e of seed.edges || []) {
    if (nodes['file:' + e.from] && nodes['file:' + e.to]) {
      edges.push(mkEdge('file:' + e.from, 'file:' + e.to, e.kind || 'derives-facts-from', 'declared', 'advisory', 'file', null))
    }
  }

  // symlink alias edges (causal basis: symlink — the alias IS the canonical file's content)
  for (const s of symlinks) {
    if (nodes['file:' + s.to]) edges.push(mkEdge('file:' + s.from, 'file:' + s.to, 'alias-of', 'symlink', 'mechanical', 'file', null))
  }

  // tag each file/symlink node with its declared zone + intent (the graph DOCUMENTS the intention)
  const zones = loadZones()
  for (const id of Object.keys(nodes)) {
    if (!id.startsWith('file:')) continue
    const z = zoneOf(id.slice(5), zones)
    if (z) { nodes[id].zone = z.intent; nodes[id].visibility = z.visibility; if (z.audience) nodes[id].audience = z.audience }
  }

  const sortedNodes = {}
  for (const k of Object.keys(nodes).sort()) sortedNodes[k] = nodes[k]
  edges.sort((a, b) => (a.from + a.to + a.kind).localeCompare(b.from + b.to + b.kind))
  return { nodes: sortedNodes, edges, anchorErrors }
}

function serialize(graph) {
  return JSON.stringify(
    { _comment: 'GENERATED by meta/build-depgraph.mjs — do not hand-edit. Edit code/markers/depgraph.seed.json and regenerate. Edge arrow: from=dependent -> to=source-of-truth.', nodes: graph.nodes, edges: graph.edges },
    null, 2,
  ) + '\n'
}

// reverse reachability: all dependents of the seed node-set
function dependentsOf(graph, seeds) {
  const rev = new Map()
  for (const e of graph.edges) {
    if (!rev.has(e.to)) rev.set(e.to, [])
    rev.get(e.to).push(e)
  }
  const out = []
  const seen = new Set(seeds)
  let frontier = [...seeds]
  while (frontier.length) {
    const next = []
    for (const src of frontier) for (const e of rev.get(src) || []) {
      if (seen.has(e.from)) continue
      seen.add(e.from)
      out.push({ node: e.from, kind: e.kind, propagation: e.propagation, granularity: e.granularity, via: e.via || null, fromSource: src })
      next.push(e.from)
    }
    frontier = next
  }
  return out
}

// --- main ---
const rawArgv = process.argv.slice(2)
const _ri = rawArgv.indexOf('--repo')
const argv = _ri >= 0 ? rawArgv.filter((_, k) => k !== _ri && k !== _ri + 1) : rawArgv
const flagVal = (n) => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : null }

// --- change detection (repo-agnostic: pure git + per-fact hashing; no repo-specific names) ---
// Paths changed since <ref>: committed range + staged + unstaged + untracked.
function gitChanged(ref) {
  const g = (a) => { try { return execFileSync('git', ['-C', ROOT, ...a], { encoding: 'utf8' }).split('\n').filter(Boolean) } catch { return [] } }
  return [...new Set([...g(['diff', '--name-only', ref, 'HEAD']), ...g(['diff', '--name-only']), ...g(['diff', '--name-only', '--cached']), ...g(['ls-files', '--others', '--exclude-standard'])])]
}
// Facts of a steward file as it stood at <ref>, for since-comparison.
function factsAt(ref, path) {
  try { return extractFacts(path, execFileSync('git', ['-C', ROOT, 'show', `${ref}:${path}`], { encoding: 'utf8' })) } catch { return {} }
}
// Seeds for explicit targets (paths or path#fact); steward facts compared working-tree vs the committed graph.
function seedsFromTargets(targets, graph) {
  const seeds = new Set()
  const changedFacts = []
  for (const t of targets) {
    if (t.includes('#')) {
      const id = 'fact:' + t
      if (graph.nodes[id]) seeds.add(id)
      else console.error(`(warning: fact node not found: ${id})`)
      continue
    }
    if (graph.nodes['file:' + t]) seeds.add('file:' + t)
    for (const id of Object.keys(graph.nodes)) if (id.startsWith(`block:${t}#`)) seeds.add(id)
    if (FACTS[t]) {
      let cur = ''
      try { cur = readFileSync(resolve(ROOT, t), 'utf8') } catch {}
      for (const [fid, h] of Object.entries(extractFacts(t, cur))) if (graph.nodes[fid] && graph.nodes[fid].hash !== h) { seeds.add(fid); changedFacts.push(fid) }
    }
  }
  return { seeds, changedFacts }
}
// Seeds for everything changed since <ref>; steward facts compared at <ref> vs now (early-cutoff).
function seedsForChange(ref, paths, graph) {
  const seeds = new Set()
  const changedFacts = []
  for (const t of paths) {
    if (graph.nodes['file:' + t]) seeds.add('file:' + t)
    for (const id of Object.keys(graph.nodes)) if (id.startsWith(`block:${t}#`)) seeds.add(id)
    if (FACTS[t]) {
      let cur = ''
      try { cur = readFileSync(resolve(ROOT, t), 'utf8') } catch {}
      const now = extractFacts(t, cur)
      const old = factsAt(ref, t)
      for (const fid of new Set([...Object.keys(now), ...Object.keys(old)])) if (now[fid] !== old[fid]) { if (graph.nodes[fid]) seeds.add(fid); changedFacts.push(fid) }
    }
  }
  return { seeds, changedFacts }
}

if (argv[0] === '--externalities') {
  // machine-local path leaks in PUBLIC files (private/ excluded; mycelium notes are ALSO
  // public — scan with `mycelium.sh dump`). This is the no-machine-local-paths rule standalone.
  const hits = []
  for (const path of listFiles()) {
    let content
    try { content = readFileSync(resolve(ROOT, path), 'utf8') } catch { continue }
    for (const h of machineLocalHits(content)) hits.push({ path, ...h })
  }
  const high = hits.filter((h) => h.sev === 'high').length
  console.log(`externalities in PUBLIC files: ${hits.length} (${high} high) across ${new Set(hits.map((h) => h.path)).size} files`)
  console.log('(public surface = unencrypted tracked files + generated docs + mycelium notes; private/ is encrypted, excluded)\n')
  for (const h of hits.sort((a, b) => (a.sev === b.sev ? a.path.localeCompare(b.path) : a.sev === 'high' ? -1 : 1))) console.log(`  [${h.sev}] ${h.path}:${h.line}  ${h.match}`)
  process.exit(0)
}

if (argv[0] === '--policy') {
  // Lint content against each file's DECLARED zone/intent (meta/zones.json).
  const zones = loadZones()
  const files = listFiles()
  const v = []
  for (const path of files) {
    const z = zoneOf(path, zones)
    if (!z) { v.push({ path, rule: 'unzoned', detail: 'no zone declared' }); continue }
    let c = null
    const content = () => { if (c === null) { try { c = readFileSync(resolve(ROOT, path), 'utf8') } catch { c = '' } } return c }
    if ((z.rules || []).includes('no-machine-local-paths')) {
      for (const h of machineLocalHits(content())) v.push({ path, zone: z.intent, rule: 'no-machine-local-paths', detail: `${h.match} (line ${h.line})` })
    }
    // no-private-operational-leak is enforced on ALL public files (listFiles excludes
    // private/), regardless of per-zone opt-in — a new public file/zone is auto-covered.
    if (z.visibility !== 'private') {
      for (const h of privateLeakHits(content())) v.push({ path, zone: z.intent, rule: 'no-private-operational-leak', detail: `${h.match} (line ${h.line})` })
    }
  }
  // must-be-ciphertext: scan the declaring zone's files for SOPS markers (private/ is excluded from listFiles)
  for (const z of zones) {
    if (!(z.rules || []).includes('must-be-ciphertext')) continue
    let pf = []
    try { pf = execFileSync('git', ['-C', ROOT, 'ls-files', z.path], { encoding: 'utf8' }).split('\n').filter(Boolean) } catch {}
    for (const f of pf) {
      let c = ''
      try { c = readFileSync(resolve(ROOT, f), 'utf8') } catch { continue }
      if (!/sops|ENC\[|-----BEGIN (PGP|AGE)/.test(c)) v.push({ path: f, zone: z.intent, rule: 'must-be-ciphertext', detail: 'appears to be plaintext (no SOPS markers)' })
    }
  }
  // no-public->private-deps: any edge from a non-private node into private/
  const g = build()
  for (const e of g.edges) {
    if (!e.to.includes('private/')) continue
    const fz = zoneOf(e.from.replace(/^(file:|block:|fact:)/, ''), zones)
    if (!fz || fz.visibility !== 'private') v.push({ path: e.from, zone: fz ? fz.intent : '?', rule: 'no-public->private-deps', detail: `edge -> ${e.to}` })
  }
  // report: zone coverage + violations + which advisory rules are declared-but-not-auto-enforced
  const byZone = {}
  for (const path of files) { const z = zoneOf(path, zones); const k = z ? z.intent : 'UNZONED'; byZone[k] = (byZone[k] || 0) + 1 }
  console.log('zone coverage (intent: files):')
  for (const [k, n] of Object.entries(byZone).sort()) console.log(`  ${k}: ${n}`)
  console.log(`\npolicy violations: ${v.length}`)
  for (const x of v) console.log(`  [${x.rule}] ${x.path}${x.zone ? ' (' + x.zone + ')' : ''} — ${x.detail}`)
  const MECH = ['no-machine-local-paths', 'must-be-ciphertext', 'no-public->private-deps', 'no-private-operational-leak']
  const advisory = new Set()
  for (const z of zones) for (const r of z.rules || []) if (!MECH.includes(r)) advisory.add(r)
  if (advisory.size) console.log(`\nadvisory rules (declared, not auto-enforced — manual/LLM review): ${[...advisory].join(', ')}`)
  process.exit(0)
}

if (argv[0] === '--impact') {
  const since = flagVal('--since')
  let graph
  try { graph = JSON.parse(readFileSync(OUT, 'utf8')) } catch { console.error('build depgraph.json first'); process.exit(2) }
  const targets = argv.slice(1).filter((a) => a !== '--since' && a !== since)
  if (!since && !targets.length) { console.error('usage: --impact <path|path#fact>...  OR  --impact --since <ref>'); process.exit(2) }
  const { seeds, changedFacts } = since ? seedsForChange(since, gitChanged(since), graph) : seedsFromTargets(targets, graph)
  const hits = dependentsOf(graph, seeds)
  const mech = hits.filter((h) => h.propagation === 'mechanical')
  const adv = hits.filter((h) => h.propagation === 'advisory')
  console.log(`change-impact of: ${since ? '--since ' + since : targets.join(', ')}`)
  if (changedFacts.length) console.log(`  facts changed: ${changedFacts.map((f) => f.split('#')[1]).join(', ')}`)
  console.log(`  ${hits.length} dependent(s) — ${mech.length} mechanical (regenerate/anchored), ${adv.length} advisory (review)\n`)
  if (mech.length) { console.log('  MECHANICAL:'); for (const h of mech) console.log(`    ${h.node}   [${h.kind}/${h.granularity}${h.via ? ' via ' + h.via : ''}]`) }
  if (adv.length) { console.log('\n  ADVISORY (owner reviews):'); for (const h of adv) console.log(`    ${h.node}   [${h.kind} <- ${h.fromSource}]`) }
  process.exit(0)
}

if (argv[0] === 'run' || argv[0] === 'true-up') {
  // Deterministic truing-up loop. The slow LLM prose-rewrite stays OUT (that's the agentic
  // /workflow layer). Repo-agnostic: change set from git; generators derived from the graph's
  // edges (`via`), never a hardcoded list — so this runs in any repo with the marker/seed convention.
  const since = flagVal('--since') || 'HEAD~1'
  const strict = argv.includes('--strict')
  const self = fileURLToPath(import.meta.url)
  let graph
  try { graph = JSON.parse(readFileSync(OUT, 'utf8')) } catch { console.error('build depgraph.json first: node ' + rel(self)); process.exit(2) }
  const changed = gitChanged(since)
  const { seeds, changedFacts } = seedsForChange(since, changed, graph)
  const hits = dependentsOf(graph, seeds)
  const mech = hits.filter((h) => h.propagation === 'mechanical')
  const adv = hits.filter((h) => h.propagation === 'advisory')
  console.log(`true-up since ${since}: ${changed.length} changed path(s), ${changedFacts.length} changed fact(s) → ${mech.length} mechanical / ${adv.length} advisory dependents`)
  // 1. REGENERATE mechanical dependents — run the generators the edges name (data-driven)
  const gens = [...new Set(mech.map((h) => h.via).filter(Boolean))]
  let regenFail = 0
  for (const gen of gens) {
    try { execFileSync('node', [resolve(ROOT, gen)], { stdio: 'ignore', cwd: ROOT, env: { ...process.env, TRUE_UP_REPO: ROOT } }); console.log(`  ✓ regenerated via ${gen}`) }
    catch { console.error(`  ✗ regenerate FAILED: ${gen}`); regenFail++ }
  }
  try { execFileSync('node', [self], { stdio: 'ignore', env: { ...process.env, TRUE_UP_REPO: ROOT } }) } catch {} // refresh depgraph.json itself
  // 2. ADVISORY worklist — prose a human/LLM must rewrite; this CLI never edits prose
  if (adv.length) {
    console.log(`\n  ADVISORY — ${adv.length} doc(s) need review (← which fact moved):`)
    for (const h of adv) console.log(`    ${h.node.replace('file:', '')}  ←  ${h.fromSource.replace('fact:', '')}`)
  } else { console.log('  advisory: none') }
  // 3. VERIFY — repo-agnostic gate: policy clean + graph self-consistent
  let pol = ''
  try { pol = execFileSync('node', [self, '--policy'], { encoding: 'utf8', env: { ...process.env, TRUE_UP_REPO: ROOT } }) } catch (e) { pol = (e.stdout || '') }
  const policyClean = /policy violations: 0\b/.test(pol)
  let chk = false
  try { execFileSync('node', [self, '--check'], { stdio: 'ignore', env: { ...process.env, TRUE_UP_REPO: ROOT } }); chk = true } catch {}
  const green = regenFail === 0 && policyClean && chk
  console.log(`\n  verify: regen ${regenFail === 0 ? 'ok' : 'FAILED'} · policy ${policyClean ? 'clean' : 'VIOLATIONS'} · depgraph ${chk ? 'in-sync' : 'STALE'} → ${green ? 'GREEN ✓' : 'NOT GREEN ✗'}`)
  if (green && adv.length) console.log('  (mechanical trued up; advisory prose review still pending — that is the /workflow layer)')
  if (!green) process.exit(1)
  if (strict && adv.length) process.exit(2)
  process.exit(0)
}

const graph = build()
// FAIL LOUD on unresolved anchors (build and --check)
if (graph.anchorErrors.length) {
  console.error('ANCHOR ERROR — these <!-- fact: … --> anchors do not resolve to a known fact node:')
  for (const e of graph.anchorErrors) console.error(`  ${e.file}: ${e.anchor}`)
  console.error('Fix the anchor path (or add the fact) and rerun. (stable-ID discipline: a wrong anchor must not pass silently.)')
  process.exit(1)
}

if (argv[0] === '--check') {
  let cur = ''
  try { cur = readFileSync(OUT, 'utf8') } catch {}
  if (cur !== serialize(graph)) { console.error('meta/depgraph.json is STALE. Regenerate with: node meta/build-depgraph.mjs'); process.exit(1) }
  console.log('meta/depgraph.json is up to date ✓')
  process.exit(0)
}

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, serialize(graph))
const nNodes = Object.keys(graph.nodes).length
const nFacts = Object.keys(graph.nodes).filter((k) => k.startsWith('fact:')).length
const byBasis = graph.edges.reduce((a, e) => ((a[e.directionBasis] = (a[e.directionBasis] || 0) + 1), a), {})
console.log(`meta/depgraph.json written: ${nNodes} nodes (${nFacts} fact-nodes), ${graph.edges.length} edges`)
console.log(`  edges by direction-basis: ${JSON.stringify(byBasis)}`)
