#!/usr/bin/env node
// true-up — build (or --check, or query --impact) the typed dependency graph of a repo.
//
//   true-up                                  # (re)write the graph JSON (path from .true-up.json `out`)
//   true-up --check                          # exit 1 if the ON-DISK graph is stale (working-tree freshness)
//   true-up --check --committed              # exit 1 if the COMMITTED/STAGED graph blob is stale (the drift gate)
//   true-up --impact <path|path#fact>...     # who is made stale (add --since <ref> for a change range)
//   true-up --policy        [--report]       # zone/visibility lint; EXIT 1 on violations (--report = exit 0)
//   true-up --externalities [--report]       # machine-local-path leak scan; EXIT 1 on leaks (--report = exit 0)
//   true-up run [--since <ref>] [--strict]   # deterministic truing-up loop (regenerate + verify); exit 1 if not GREEN
//   true-up init                             # scaffold a starter .true-up.json
//   true-up --help                           # this help (writes nothing)
//
// All paths/targets are relative to the TARGET repo: --repo <path> | $TRUE_UP_REPO | git toplevel of CWD | CWD.
//
// LAYER 2 (detection). A typed, content-hashed, *directed* dependency graph spanning
// code + data + prose, whose edges carry a CAUSAL direction (from = dependent /
// downstream, to = source-of-truth).
//
// Direction never comes from correlation. Only from a causal basis:
//   - generator : a build script's input->output, from the self-describing
//                 "generated by X from Y" markers already in the repo.    (mechanical)
//   - declared  : a steward registry in .true-up.json `seed`.            (advisory)
//   - anchored  : an inline marker in the dependent pointing at a FACT
//                 (<!-- fact: <path>#<arrayProp>.<key> -->).             (mechanical, fact-granular)
// Correlation signals (co-change / embeddings) may only PROPOSE undirected
// candidates; they never assign the arrow, so none are emitted here.
//
// Granularity: steward data files are decomposed into per-fact nodes (content-hashed
// individually) so an anchored dependent is only stale when THAT fact's hash moves
// (early-cutoff) — not when any unrelated part of the file changes.
//
// Fail-loud: an anchor whose fact path does not resolve is a hard error (aplumb's
// "stable IDs, fail on mismatch" lesson) — a silently-wrong anchor is worse than none.
//
// Zero-dep node, deterministic output (sorted, no timestamps) so --check is honest.

import { readFileSync, writeFileSync, mkdirSync, existsSync, lstatSync, readlinkSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, relative } from 'node:path'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'

const self = fileURLToPath(import.meta.url)
const here = (p) => resolve(dirname(self), p)

// This is the TOOL: it operates on a TARGET repo, not its own directory.
// Target = --repo <path> | $TRUE_UP_REPO | git toplevel of CWD | CWD.
function resolveRoot() {
  const i = process.argv.indexOf('--repo')
  if (i >= 0 && process.argv[i + 1]) return resolve(process.argv[i + 1])
  if (process.env.TRUE_UP_REPO) return resolve(process.env.TRUE_UP_REPO)
  try { return execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim() } catch { return process.cwd() }
}
const ROOT = resolveRoot()

// Per-repo config: <ROOT>/.true-up.json (or true-up.config.json) declares stewards (facts),
// zones, declared edges, and the output path. Everything repo-specific lives here, not in code.
function loadConfig() {
  for (const name of ['.true-up.json', 'true-up.config.json']) {
    try { return JSON.parse(readFileSync(resolve(ROOT, name), 'utf8')) } catch {}
  }
  return {}
}
const CONFIG = loadConfig()
const OUT = resolve(ROOT, CONFIG.out || '.true-up/depgraph.json')
// steward files decomposed into per-fact nodes: path -> [ [arrayProp, keyField] ]  (from config)
const FACTS = CONFIG.facts || {}

const sha256 = (s) => createHash('sha256').update(s).digest('hex').slice(0, 16)
const rel = (abs) => relative(ROOT, abs)
// User-facing "rebuild" hint. When invoked cross-repo (--repo), the engine path relative to the
// TARGET ascends out of it ("../../…/bin"), which is confusing guidance — fall back to the command name.
const rebuildHint = relative(ROOT, self).startsWith('..') ? 'true-up' : relative(ROOT, self)

// deep key-sorted stringify so a fact's hash is order-independent
function sortKeys(v) {
  if (Array.isArray(v)) return v.map(sortKeys)
  if (v && typeof v === 'object') {
    const o = {}
    for (const k of Object.keys(v).sort()) o[k] = sortKeys(v[k])
    return o
  }
  return v
}
const stable = (v) => JSON.stringify(sortKeys(v))
// Blank out fenced + inline code so syntax shown in DOCUMENTATION (a doc explaining true-up's own
// <!-- fact: --> / generated-by markers, OR a privacy policy quoting a forbidden path shape) is never
// parsed as a live anchor/marker or flagged as a leak. Preserves line count (replaces non-newline
// chars with spaces) so line numbers stay accurate.
const stripCode = (s) => s.replace(/```[\s\S]*?```/g, (m) => m.replace(/[^\n]/g, ' ')).replace(/`[^`\n]+`/g, (m) => ' '.repeat(m.length))

// Per-line suppression: a legitimate path-example in prose (e.g. the privacy policy itself) can opt out.
//   <!-- true-up:ignore-line [rule] -->   suppresses findings on THIS line
//   <!-- true-up:ignore-next [rule] -->   suppresses findings on the NEXT line
// Optional [rule] (e.g. no-machine-local-paths) scopes it; omitted = all rules. Checked against the
// ORIGINAL line text (so the directive is seen even if stripCode would blank a code span around it).
const SUPPRESS_LINE = /<!--\s*true-up:ignore-line(?:\s+([\w-]+))?\s*-->/
const SUPPRESS_NEXT = /<!--\s*true-up:ignore-next(?:\s+([\w-]+))?\s*-->/
function suppressor(origLines) {
  return (i, rule) => {
    const ml = (origLines[i] || '').match(SUPPRESS_LINE)
    if (ml && (!ml[1] || ml[1] === rule)) return true
    const mn = (i > 0 ? origLines[i - 1] || '' : '').match(SUPPRESS_NEXT)
    if (mn && (!mn[1] || mn[1] === rule)) return true
    return false
  }
}

// ---- zones / policy ----
function loadZones() {
  // default: one public-default zone so --policy enforces no-machine-local-paths everywhere out of the box
  return CONFIG.zones || [{ path: '', visibility: 'public', audience: 'world', intent: 'public-default', rules: ['no-machine-local-paths'] }]
}
function zoneScore(zpath, path) {
  if (zpath === path) return 1000
  if (zpath.startsWith('**/') && path.endsWith(zpath.slice(2))) return 600 + zpath.length
  if (zpath.startsWith('*') && path.endsWith(zpath.slice(1))) return 500 + zpath.length
  if (zpath.endsWith('/') && path.startsWith(zpath)) return 100 + zpath.length
  if (zpath === '' || zpath === '/') return 1
  return -1
}
function zoneOf(path, zones) {
  let best = null
  let bestS = 0
  for (const z of zones) { const s = zoneScore(z.path, path); if (s > bestS) { bestS = s; best = z } }
  return best
}
// machine-local path leaks (canonical ~/.claude etc. allowlisted). Scans stripCode'd content
// (doc code-spans are illustrative, not leaks) and honors per-line suppression directives.
const EXT_PATS = [
  { re: /\/home\/[a-z][\w.\-]*\//gi, sev: 'high' },
  { re: /\/Users\/[A-Za-z][\w.\-]*\//g, sev: 'high' },
  { re: /(?<![$\w])~\/[\w./\-]+/g, sev: 'med' },
]
const EXT_ALLOW = [/^~\/\.(claude|config|cache)\b/]
function machineLocalHits(content) {
  const orig = content.split('\n')
  const scan = stripCode(content).split('\n')
  const sup = suppressor(orig)
  const hits = []
  scan.forEach((line, i) => {
    if (sup(i, 'no-machine-local-paths')) return
    for (const p of EXT_PATS) {
      p.re.lastIndex = 0
      let m
      while ((m = p.re.exec(line))) { if (EXT_ALLOW.some((a) => a.test(m[0]))) continue; hits.push({ line: i + 1, sev: p.sev, match: m[0] }) }
    }
  })
  return hits
}

// Private OPERATIONAL/AUTH mechanics that must never appear in a PUBLIC file. This is
// the `share-method-not-operator` advisory PROMOTED to a mechanical rule for the
// concrete tokens that have leaked or are unambiguously operator/auth detail. Naming a
// provider as a sanitized conclusion (a "subscription bridge", a model slug) is allowed
// and intentionally NOT matched; its AUTH MECHANICS — credential file paths, private
// adapter class names, raw backend endpoints — are what leak. Add a token the moment a
// new class of operational detail is found in a public file (harness rule: a leak that
// happened once becomes a lint that can't happen again).
//
// The banned literals are ASSEMBLED FROM FRAGMENTS so this definition never contains a
// contiguous banned token — the rule polices itself without self-tripping (same spirit
// as the escaped machine-local regexes above). Reword comments/docs, never inline a
// literal, when extending this list.
const _leak = (s) => new RegExp(s, 'i')
const PRIVATE_LEAK_PATS = [
  _leak('auth' + '\\.' + 'json'),                        // a credential JSON file
  _leak('\\.cod' + 'ex/auth|\\.pi/' + 'agent'),          // agent-CLI credential directories
  _leak('back' + 'end-api|chatgpt\\.com/back' + 'end'),  // raw subscription backend endpoint
  new RegExp('Codex' + 'SubscriptionLM'),                // a private adapter class name
]
function privateLeakHits(content) {
  const orig = content.split('\n')
  const scan = stripCode(content).split('\n')
  const sup = suppressor(orig)
  const hits = []
  scan.forEach((line, i) => {
    if (sup(i, 'no-private-operational-leak')) return
    for (const re of PRIVATE_LEAK_PATS) {
      const m = re.exec(line)
      if (m) hits.push({ line: i + 1, match: m[0] })
    }
  })
  return hits
}

// per-fact hashes for a steward file -> { factId: hash }
function extractFacts(path, content) {
  const out = {}
  const spec = FACTS[path]
  if (!spec) return out
  let data
  try { data = JSON.parse(content) } catch { return out }
  for (const [arrProp, keyField] of spec) {
    const arr = data[arrProp]
    if (!Array.isArray(arr)) continue
    for (const item of arr) {
      const key = item && item[keyField]
      if (key === null || key === undefined) continue
      out[`fact:${path}#${arrProp}.${key}`] = sha256(stable(item))
    }
  }
  return out
}

const gitLines = (args) => {
  try { return execFileSync('git', ['-C', ROOT, ...args], { encoding: 'utf8' }).split('\n').filter(Boolean) }
  catch { return [] }
}
function listFiles() {
  const all = [...new Set([...gitLines(['ls-files']), ...gitLines(['ls-files', '--others', '--exclude-standard'])])]
  const KEEP = /\.(md|json|mjs|js)$/
  const SKIP = /^(private\/|node_modules\/|\.git\/|\.jj\/|\.true-up\/)|^\.true-up\.json$|^true-up\.config\.json$|depgraph\.(json|seed\.json)$/
  return all.filter((p) => KEEP.test(p) && !SKIP.test(p)).sort()
}

const extKind = (p) => /\.(mjs|js|py|ts|tsx|rb|go|rs|sh|c|cc|cpp|h|java|kt|swift)$/.test(p) ? 'code' : p.endsWith('.json') ? 'data' : 'prose'

function classify(path, content) {
  if (/\.(mjs|js)$/.test(path)) return { kind: 'code', role: 'none' }
  if (path.endsWith('.json')) {
    if (FACTS[path]) return { kind: 'data', role: 'steward' }
    return { kind: 'data', role: 'none' }
  }
  if (/^<!--\s*generated by /m.test(content.slice(0, 400))) return { kind: 'generated', role: 'guard' }
  if (path.endsWith('SKILL.md')) return { kind: 'prose', role: 'writer', audience: 'external-agents' }
  if (path === 'README.md' || /\/README\.md$/.test(path)) return { kind: 'prose', role: 'writer', audience: 'users' }
  if (path === 'AGENTS.md') return { kind: 'prose', role: 'writer', audience: 'maintainers' }
  return { kind: 'prose', role: 'writer', audience: 'mixed' }
}

// Resolve a generator's input file from its `here('./X.json')` literal, relative to the
// generator's own directory (not a hardcoded prefix), so generators live anywhere.
function generatorSource(genRel) {
  try {
    const m = readFileSync(resolve(ROOT, genRel), 'utf8').match(/here\(['"]\.\/([\w.\-]+\.json)['"]\)/)
    if (m) return rel(resolve(ROOT, dirname(genRel), m[1]))
  } catch {}
  return null
}

function mkEdge(from, to, kind, directionBasis, propagation, granularity, via) {
  return { from, to, kind, directionBasis, propagation, granularity, ...(via ? { via } : {}) }
}

function build() {
  const files = listFiles()
  const nodes = {}
  const edges = []
  const contents = {}
  const anchorErrors = []
  const symlinks = []

  for (const path of files) {
    const abs = resolve(ROOT, path)
    let st
    try { st = lstatSync(abs) } catch { continue }
    if (st.isSymbolicLink()) {
      // a symlink is an ALIAS of its target (e.g. CLAUDE.md -> AGENTS.md): same bytes,
      // one canonical source. Do NOT read the followed content as an independent node.
      let targetRel = null
      try { targetRel = rel(resolve(dirname(abs), readlinkSync(abs))) } catch {}
      nodes['file:' + path] = { kind: 'symlink', role: 'alias', ...(targetRel ? { symlinkTo: targetRel } : {}), hash: sha256('symlink->' + (targetRel || '?')) }
      if (targetRel) symlinks.push({ from: path, to: targetRel })
      continue
    }
    let content
    try { content = readFileSync(abs, 'utf8') } catch { continue }
    contents[path] = content
    const m = classify(path, content)
    nodes['file:' + path] = { kind: m.kind, role: m.role, ...(m.audience ? { audience: m.audience } : {}), hash: sha256(content) }
    // decompose steward data files into per-fact nodes
    for (const [factId, h] of Object.entries(extractFacts(path, content))) {
      nodes[factId] = { kind: 'fact', role: 'steward-fact', hash: h }
    }
  }

  for (const path of files) {
    const content = contents[path]
    if (!content) continue
    if (/\.(mjs|js)$/.test(path)) continue // code files carry marker strings as literals
    const scan = stripCode(content) // markers/anchors inside code formatting are docs, not live
    // whole-file generated marker
    const whole = scan.match(/<!--\s*generated by\s+([^\s)]+)(?:\s+from\s+([^\s)]+))?/)
    if (whole && /^<!--\s*generated by /m.test(scan.slice(0, 400))) {
      const source = whole[2] || generatorSource(whole[1])
      if (source && nodes['file:' + source]) edges.push(mkEdge('file:' + path, 'file:' + source, 'generated-from', 'generator', 'mechanical', 'file', whole[1]))
    }
    // generated BLOCK marker
    const blk = scan.match(/<!--\s*([A-Z]+):START\s*\(generated by\s+([^\s)]+)[^]*?-->([^]*?)<!--\s*\1:END\s*-->/)
    if (blk) {
      const [, tag, gen, body] = blk
      const source = generatorSource(gen)
      nodes[`block:${path}#${tag}`] = { kind: 'generated', role: 'guard', hash: sha256(body) }
      if (source && nodes['file:' + source]) edges.push(mkEdge(`block:${path}#${tag}`, 'file:' + source, 'generated-from', 'generator', 'mechanical', 'span', gen))
    }
    // anchored fact markers -> directed, fact-granular, mechanical (FAIL LOUD if unresolved)
    for (const m of scan.matchAll(/<!--\s*fact:\s*([\w./\-]+#[\w.\-]+)\s*-->/g)) {
      const factId = 'fact:' + m[1]
      // anchored prose dep: fact-GRANULAR (fires only on that fact) but ADVISORY (a human/LLM
      // rewrites the prose) — only generated-from is mechanical/regenerable.
      if (nodes[factId]) edges.push(mkEdge('file:' + path, factId, 'derives-facts-from', 'anchored', 'advisory', 'fact', null))
      else anchorErrors.push({ file: path, anchor: m[1] })
    }
  }

  // declared edges (file granularity, advisory) from the steward registry. A declared edge may
  // reference a tracked source file that is NOT a graph node by default (e.g. a .py registry); add a
  // minimal node for such an endpoint so the coarse edge is not silently dropped (report LIMITATION).
  const tracked = new Set(gitLines(['ls-files']))
  for (const e of CONFIG.seed || []) {
    for (const ep of [e.from, e.to]) {
      const id = 'file:' + ep
      if (!nodes[id] && tracked.has(ep)) {
        let c = ''
        try { c = readFileSync(resolve(ROOT, ep), 'utf8') } catch {}
        nodes[id] = { kind: extKind(ep), role: 'none', hash: sha256(c) }
      }
    }
    if (nodes['file:' + e.from] && nodes['file:' + e.to]) {
      edges.push(mkEdge('file:' + e.from, 'file:' + e.to, e.kind || 'derives-facts-from', 'declared', 'advisory', 'file', null))
    }
  }

  // symlink alias edges (causal basis: symlink — the alias IS the canonical file's content)
  for (const s of symlinks) {
    if (nodes['file:' + s.to]) edges.push(mkEdge('file:' + s.from, 'file:' + s.to, 'alias-of', 'symlink', 'mechanical', 'file', null))
  }

  // tag each file/symlink node with its declared zone + intent (the graph DOCUMENTS the intention)
  const zones = loadZones()
  for (const id of Object.keys(nodes)) {
    if (!id.startsWith('file:')) continue
    const z = zoneOf(id.slice(5), zones)
    if (z) { nodes[id].zone = z.intent; nodes[id].visibility = z.visibility; if (z.audience) nodes[id].audience = z.audience }
  }

  const sortedNodes = {}
  for (const k of Object.keys(nodes).sort()) sortedNodes[k] = nodes[k]
  edges.sort((a, b) => (a.from + a.to + a.kind).localeCompare(b.from + b.to + b.kind))
  return { nodes: sortedNodes, edges, anchorErrors }
}

function serialize(graph) {
  return JSON.stringify(
    { _comment: 'GENERATED by true-up (do not hand-edit). Edit sources/markers/.true-up.json seed and regenerate. Edge arrow: from=dependent -> to=source-of-truth.', nodes: graph.nodes, edges: graph.edges },
    null, 2,
  ) + '\n'
}

// reverse reachability: all dependents of the seed node-set
function dependentsOf(graph, seeds) {
  const rev = new Map()
  for (const e of graph.edges) {
    if (!rev.has(e.to)) rev.set(e.to, [])
    rev.get(e.to).push(e)
  }
  const out = []
  const seen = new Set(seeds)
  let frontier = [...seeds]
  while (frontier.length) {
    const next = []
    for (const src of frontier) for (const e of rev.get(src) || []) {
      if (seen.has(e.from)) continue
      seen.add(e.from)
      out.push({ node: e.from, kind: e.kind, propagation: e.propagation, granularity: e.granularity, via: e.via || null, fromSource: src })
      next.push(e.from)
    }
    frontier = next
  }
  return out
}

// --- main ---
const rawArgv = process.argv.slice(2)
const JSONOUT = rawArgv.includes('--json') // Axiom 8: structured output one flag away (stdout=data)
const _ri = rawArgv.indexOf('--repo')
const argv = (_ri >= 0 ? rawArgv.filter((_, k) => k !== _ri && k !== _ri + 1) : rawArgv).filter((a) => a !== '--json')
const flagVal = (n) => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : null }
const refExists = (ref) => { try { execFileSync('git', ['-C', ROOT, 'rev-parse', '--verify', '--quiet', ref + '^{commit}'], { stdio: 'ignore' }); return true } catch { return false } }
const VERSION = (() => { try { return JSON.parse(readFileSync(here('../package.json'), 'utf8')).version } catch { return '0.0.0' } })()
const jout = (obj) => process.stdout.write(JSON.stringify(obj, null, 2) + '\n') // pure JSON to stdout
// Structure-aware SOPS/age/pgp ciphertext detection — NOT a bare "sops" substring (a plaintext file
// that merely mentions sops must FAIL must-be-ciphertext). Real markers: sops value-encryption
// ENC[CIPHER,…], a sops `mac` field bound to ENC[…], or full-file age/pgp armor.
const isCiphertext = (c) => /ENC\[(AES256_GCM|CHACHA20_POLY1305),/.test(c) || /-----BEGIN (PGP MESSAGE|AGE ENCRYPTED FILE)-----/.test(c) || /(^|[\s"'])mac["']?\s*[:=]\s*["']?ENC\[/m.test(c)
// Intent inference (Axiom 7): a mistyped command gets a surgical "did you mean" instead of a dead end.
const KNOWN_CMDS = ['--check', '--impact', '--policy', '--externalities', 'run', '--verify-scope', 'init', 'capabilities', '--version', '--help', 'help']
const lev = (a, b) => {
  const d = Array.from({ length: a.length + 1 }, (_, i) => [i, ...Array(b.length).fill(0)])
  for (let j = 0; j <= b.length; j++) d[0][j] = j
  for (let i = 1; i <= a.length; i++) for (let j = 1; j <= b.length; j++) d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1))
  return d[a.length][b.length]
}
const didYouMean = (w) => { let best = null, bd = 99; for (const c of KNOWN_CMDS) { const dd = lev(w, c); if (dd < bd) { bd = dd; best = c } } return bd <= 3 ? best : null }

const HELP = `true-up — deterministic, content-hashed dependency-graph + truing-up gate.

  true-up                                  (re)write the graph JSON (path from .true-up.json "out")
  true-up --check [--committed]            stale-graph gate (on-disk; --committed = committed-blob drift gate)
  true-up --impact <path|path#fact>...     who is made stale  (add --since <ref> for a change range)
  true-up --policy        [--report]       zone/visibility + leak lint; EXIT 1 on violations (--report = exit 0)
  true-up --externalities [--report]       machine-local-path leak scan; EXIT 1 on leaks (--report = exit 0)
  true-up --verify-scope [--since <ref>]   anti-code-golf gate: EXIT 1 if a changed file is not explained by the graph
  true-up run [--since <ref>] [--strict]   deterministic truing-up loop; EXIT 1 if not GREEN
  true-up init                             scaffold a starter .true-up.json
  true-up capabilities                     machine-readable contract (commands, flags, exit codes) — always JSON
  true-up --version | --help               version / this help (write nothing)

  --repo <path>   operate on another repo (default: $TRUE_UP_REPO | git toplevel of CWD | CWD)
  --json          structured output to stdout (data only) on every read-side command

Exit codes:  0 = success / clean / GREEN    1 = gate violation (stale / leak / policy / not-GREEN / out-of-scope)    2 = usage error (unknown command / bad --since ref / graph not built)

Config: <repo>/.true-up.json (facts, zones, seed edges, out). See docs/CONFIG.md.
Suppress a legit path-example in prose: <!-- true-up:ignore-line [rule] --> (or ignore-next).
`

if (argv[0] === '--help' || argv[0] === '-h' || argv[0] === 'help') { process.stdout.write(HELP); process.exit(0) }

if (argv[0] === '--version' || argv[0] === '-v') { process.stdout.write(`true-up ${VERSION}\n`); process.exit(0) }

// Axiom 9: the contract is readable from the tool — an agent never has to remember it out-of-band.
if (argv[0] === 'capabilities') {
  jout({
    tool: 'true-up',
    version: VERSION,
    contract_version: 1,
    description: 'deterministic, content-hashed dependency-graph + truing-up gate',
    commands: [
      { name: '(no args)', summary: '(re)write the graph JSON', json: true, exits: [0, 2] },
      { name: '--check [--committed]', summary: 'stale-graph gate (working-tree, or committed-blob drift gate)', json: true, exits: [0, 1] },
      { name: '--impact <path|path#fact>... [--since <ref>]', summary: 'who is made stale', json: true, exits: [0, 2] },
      { name: '--policy [--report]', summary: 'zone/visibility + leak lint; gate', json: true, exits: [0, 1] },
      { name: '--externalities [--report]', summary: 'machine-local-path leak scan; gate', json: true, exits: [0, 1] },
      { name: '--verify-scope [--since <ref>]', summary: 'anti-code-golf gate (changed files ⊆ blast radius)', json: true, exits: [0, 1, 2] },
      { name: 'run [--since <ref>] [--strict]', summary: 'truing-up loop: detect → regen → verify', json: true, exits: [0, 1, 2] },
      { name: 'init', summary: 'scaffold a starter .true-up.json', json: false, exits: [0, 1] },
      { name: 'capabilities', summary: 'this contract (always JSON)', json: true, exits: [0] },
    ],
    global_flags: {
      '--repo <path>': 'operate on another repo (default: $TRUE_UP_REPO | git toplevel of CWD | CWD)',
      '--json': 'structured output to stdout (data only); diagnostics go to stderr',
      '--since <ref>': 'change range for --impact / run / --verify-scope',
      '--report': '--policy/--externalities print findings but exit 0 (report-only, no gating)',
      '--committed': '--check compares the committed/staged graph blob, not the on-disk one',
      '--strict': 'run exits 2 when advisory prose review is still pending',
    },
    exit_codes: {
      0: 'success / clean / GREEN',
      1: 'gate violation — stale graph, policy/leak violation, NOT GREEN, or out-of-scope edit',
      2: 'usage error — unknown command, bad --since ref, or graph not built yet',
    },
    config_file: '.true-up.json',
    out_default: '.true-up/depgraph.json',
    suppression: '<!-- true-up:ignore-line [rule] --> / <!-- true-up:ignore-next [rule] --> in prose',
    workflows: ['true-up-maintenance (default, blast-radius-scoped)', 'true-up-audit (report-only, exhaustive)'],
  })
  process.exit(0)
}

if (argv[0] === 'init') {
  const target = resolve(ROOT, '.true-up.json')
  if (existsSync(target)) { console.error(`${rel(target)} already exists — not overwriting.`); process.exit(1) }
  const starter = {
    _comment: 'true-up config. Declare steward facts, zones, and declared (seed) edges. See docs/CONFIG.md.',
    facts: {},
    zones: [
      { path: 'private/', visibility: 'private', audience: 'team', intent: 'encrypted-notes', rules: ['must-be-ciphertext'] },
      { path: '**/SKILL.md', visibility: 'public', audience: 'external-agents', intent: 'loadable-skill', rules: ['no-machine-local-paths'] },
      { path: 'README.md', visibility: 'public', audience: 'users', intent: 'user-overview', rules: ['no-machine-local-paths'] },
      { path: '', visibility: 'public', audience: 'world', intent: 'public-default', rules: ['no-machine-local-paths', 'no-public->private-deps'] },
    ],
    seed: [],
    out: '.true-up/depgraph.json',
  }
  writeFileSync(target, JSON.stringify(starter, null, 2) + '\n')
  console.log(`wrote ${rel(target)} — declare facts/zones/seed for your repo, then run: true-up`)
  process.exit(0)
}

// --- change detection (repo-agnostic: pure git + per-fact hashing; no repo-specific names) ---
// Paths changed since <ref>: committed range + staged + unstaged + untracked.
function gitChanged(ref) {
  const g = (a) => { try { return execFileSync('git', ['-C', ROOT, ...a], { encoding: 'utf8' }).split('\n').filter(Boolean) } catch { return [] } }
  return [...new Set([...g(['diff', '--name-only', ref, 'HEAD']), ...g(['diff', '--name-only']), ...g(['diff', '--name-only', '--cached']), ...g(['ls-files', '--others', '--exclude-standard'])])]
}
// Facts of a steward file as it stood at <ref>, for since-comparison.
function factsAt(ref, path) {
  try { return extractFacts(path, execFileSync('git', ['-C', ROOT, 'show', `${ref}:${path}`], { encoding: 'utf8' })) } catch { return {} }
}
// Seeds for explicit targets (paths or path#fact); steward facts compared working-tree vs the committed graph.
function seedsFromTargets(targets, graph) {
  const seeds = new Set()
  const changedFacts = []
  for (const t of targets) {
    if (t.includes('#')) {
      const id = 'fact:' + t
      if (graph.nodes[id]) seeds.add(id)
      else console.error(`(warning: fact node not found: ${id})`)
      continue
    }
    if (graph.nodes['file:' + t]) seeds.add('file:' + t)
    for (const id of Object.keys(graph.nodes)) if (id.startsWith(`block:${t}#`)) seeds.add(id)
    if (FACTS[t]) {
      let cur = ''
      try { cur = readFileSync(resolve(ROOT, t), 'utf8') } catch {}
      for (const [fid, h] of Object.entries(extractFacts(t, cur))) if (graph.nodes[fid] && graph.nodes[fid].hash !== h) { seeds.add(fid); changedFacts.push(fid) }
    }
  }
  return { seeds, changedFacts }
}
// Seeds for everything changed since <ref>; steward facts compared at <ref> vs now (early-cutoff).
function seedsForChange(ref, paths, graph) {
  const seeds = new Set()
  const changedFacts = []
  for (const t of paths) {
    if (graph.nodes['file:' + t]) seeds.add('file:' + t)
    for (const id of Object.keys(graph.nodes)) if (id.startsWith(`block:${t}#`)) seeds.add(id)
    if (FACTS[t]) {
      let cur = ''
      try { cur = readFileSync(resolve(ROOT, t), 'utf8') } catch {}
      const now = extractFacts(t, cur)
      const old = factsAt(ref, t)
      for (const fid of new Set([...Object.keys(now), ...Object.keys(old)])) if (now[fid] !== old[fid]) { if (graph.nodes[fid]) seeds.add(fid); changedFacts.push(fid) }
    }
  }
  return { seeds, changedFacts }
}

if (argv[0] === '--externalities') {
  // machine-local path leaks in PUBLIC files (private/ excluded; mycelium notes are ALSO
  // public — scan with `mycelium.sh dump`). This is the no-machine-local-paths rule standalone.
  const report = argv.includes('--report')
  const hits = []
  for (const path of listFiles()) {
    let content
    try { content = readFileSync(resolve(ROOT, path), 'utf8') } catch { continue }
    for (const h of machineLocalHits(content)) hits.push({ path, ...h })
  }
  const sorted = hits.sort((a, b) => (a.sev === b.sev ? a.path.localeCompare(b.path) : a.sev === 'high' ? -1 : 1))
  const high = sorted.filter((h) => h.sev === 'high').length
  const files = new Set(sorted.map((h) => h.path)).size
  if (JSONOUT) jout({ rule: 'no-machine-local-paths', count: sorted.length, high, files, clean: sorted.length === 0, hits: sorted })
  else {
    console.log(`externalities in PUBLIC files: ${sorted.length} (${high} high) across ${files} files`)
    console.log('(public surface = unencrypted tracked files + generated docs + mycelium notes; private/ is encrypted, excluded)\n')
    for (const h of sorted) console.log(`  [${h.sev}] ${h.path}:${h.line}  ${h.match}`)
  }
  process.exit(report ? 0 : (sorted.length ? 1 : 0))
}

if (argv[0] === '--policy') {
  // Lint content against each file's DECLARED zone/intent (from .true-up.json zones).
  const report = argv.includes('--report')
  const zones = loadZones()
  const files = listFiles()
  const v = []
  for (const path of files) {
    const z = zoneOf(path, zones)
    if (!z) { v.push({ path, rule: 'unzoned', detail: 'no zone declared' }); continue }
    let c = null
    const content = () => { if (c === null) { try { c = readFileSync(resolve(ROOT, path), 'utf8') } catch { c = '' } } return c }
    if ((z.rules || []).includes('no-machine-local-paths')) {
      for (const h of machineLocalHits(content())) v.push({ path, zone: z.intent, rule: 'no-machine-local-paths', detail: `${h.match} (line ${h.line})` })
    }
    // no-private-operational-leak is enforced on ALL public files (listFiles excludes
    // private/), regardless of per-zone opt-in — a new public file/zone is auto-covered.
    if (z.visibility !== 'private') {
      for (const h of privateLeakHits(content())) v.push({ path, zone: z.intent, rule: 'no-private-operational-leak', detail: `${h.match} (line ${h.line})` })
    }
  }
  // must-be-ciphertext: scan the declaring zone's files for SOPS markers (private/ is excluded from listFiles)
  for (const z of zones) {
    if (!(z.rules || []).includes('must-be-ciphertext')) continue
    let pf = []
    try { pf = execFileSync('git', ['-C', ROOT, 'ls-files', z.path], { encoding: 'utf8' }).split('\n').filter(Boolean) } catch {}
    for (const f of pf) {
      let c = ''
      try { c = readFileSync(resolve(ROOT, f), 'utf8') } catch { continue }
      if (!isCiphertext(c)) v.push({ path: f, zone: z.intent, rule: 'must-be-ciphertext', detail: 'appears to be plaintext (no SOPS/age/pgp ciphertext structure — a bare "sops" mention does not count)' })
    }
  }
  // no-public->private-deps: any edge from a non-private node into private/
  const g = build()
  for (const e of g.edges) {
    if (!e.to.includes('private/')) continue
    const fz = zoneOf(e.from.replace(/^(file:|block:|fact:)/, ''), zones)
    if (!fz || fz.visibility !== 'private') v.push({ path: e.from, zone: fz ? fz.intent : '?', rule: 'no-public->private-deps', detail: `edge -> ${e.to}` })
  }
  // report: zone coverage + violations + which advisory rules are declared-but-not-auto-enforced
  const byZone = {}
  for (const path of files) { const z = zoneOf(path, zones); const k = z ? z.intent : 'UNZONED'; byZone[k] = (byZone[k] || 0) + 1 }
  const MECH = ['no-machine-local-paths', 'must-be-ciphertext', 'no-public->private-deps', 'no-private-operational-leak']
  const advisory = new Set()
  for (const z of zones) for (const r of z.rules || []) if (!MECH.includes(r)) advisory.add(r)
  // no-private-operational-leak is enforced on EVERY public file regardless of zone opt-in — surface it
  // so a reader never mistakes "not in my zone's rules" for "not checked".
  const alwaysEnforced = ['no-private-operational-leak']
  if (JSONOUT) jout({ count: v.length, clean: v.length === 0, violations: v, zoneCoverage: byZone, enforcedRules: MECH, alwaysEnforced, advisoryRules: [...advisory] })
  else {
    console.log('zone coverage (intent: files):')
    for (const [k, n] of Object.entries(byZone).sort()) console.log(`  ${k}: ${n}`)
    console.log(`\npolicy violations: ${v.length}`)
    for (const x of v) console.log(`  [${x.rule}] ${x.path}${x.zone ? ' (' + x.zone + ')' : ''} — ${x.detail}`)
    console.log(`\nalways enforced on public files (not zone-opt-in): ${alwaysEnforced.join(', ')}`)
    if (advisory.size) console.log(`advisory rules (declared, not auto-enforced — manual/LLM review): ${[...advisory].join(', ')}`)
  }
  process.exit(report ? 0 : (v.length ? 1 : 0))
}

if (argv[0] === '--impact') {
  const since = flagVal('--since')
  if (since && !refExists(since)) { console.error(`bad git ref: ${since} (does not resolve to a commit). Not the same as "0 dependents".`); process.exit(2) }
  let graph
  try { graph = JSON.parse(readFileSync(OUT, 'utf8')) } catch { console.error(`build the graph first: ${rebuildHint}`); process.exit(2) }
  const targets = argv.slice(1).filter((a) => a !== '--since' && a !== since)
  if (!since && !targets.length) { console.error('usage: --impact <path|path#fact>...  OR  --impact --since <ref>'); process.exit(2) }
  const { seeds, changedFacts } = since ? seedsForChange(since, gitChanged(since), graph) : seedsFromTargets(targets, graph)
  const hits = dependentsOf(graph, seeds)
  const mech = hits.filter((h) => h.propagation === 'mechanical')
  const adv = hits.filter((h) => h.propagation === 'advisory')
  if (JSONOUT) jout({ target: since ? { since } : { targets }, changedFacts, counts: { total: hits.length, mechanical: mech.length, advisory: adv.length }, mechanical: mech, advisory: adv })
  else {
    console.log(`change-impact of: ${since ? '--since ' + since : targets.join(', ')}`)
    if (changedFacts.length) console.log(`  facts changed: ${changedFacts.map((f) => f.split('#')[1]).join(', ')}`)
    console.log(`  ${hits.length} dependent(s) — ${mech.length} mechanical (regenerate/anchored), ${adv.length} advisory (review)\n`)
    if (mech.length) { console.log('  MECHANICAL:'); for (const h of mech) console.log(`    ${h.node}   [${h.kind}/${h.granularity}${h.via ? ' via ' + h.via : ''}]`) }
    if (adv.length) { console.log('\n  ADVISORY (owner reviews):'); for (const h of adv) console.log(`    ${h.node}   [${h.kind} <- ${h.fromSource}]`) }
  }
  process.exit(0)
}

if (argv[0] === '--verify-scope') {
  // The deterministic anti-code-golf gate. After a maintenance edit, EVERY changed file must be
  // "explained" by the dependency graph relative to <ref>: it is a changed source-of-truth, OR a
  // regenerated/advisory dependent of one, OR the graph cache. A changed file that is neither (an
  // out-of-blast-radius edit — e.g. an unanchored doc someone "tidied" because it mentions the
  // changed term) is scope creep / code-golf and FAILS the gate. Undeclared staleness is the
  // audit's job (it proposes an anchor), not maintenance's. Empirically: without this an LLM
  // expanded scope to such decoys 3/3 trials; with the worklist-subset discipline, 0/3.
  const since = flagVal('--since') || 'HEAD'
  if (!refExists(since)) { console.error(`bad git ref: ${since}`); process.exit(2) }
  const g = build()
  if (!g.edges.length) {
    if (JSONOUT) jout({ ok: true, vacuous: true, reason: 'no dependency edges declared — declare facts/seed in .true-up.json', changed: [], violations: [] })
    else console.error('NOTE: no dependency edges declared — scope check is vacuous (PASS ≠ GUARDED). Declare facts/seed in .true-up.json; see docs/CONFIG.md.')
    process.exit(0)
  }
  const srcFile = (id) => id.startsWith('file:') ? id.slice(5) : id.startsWith('fact:') ? id.slice(5).split('#')[0] : id.startsWith('block:') ? id.slice(6).split('#')[0] : null
  const sources = new Set()
  for (const e of g.edges) { const s = srcFile(e.to); if (s) sources.add(s) }
  const KEEP = /\.(md|json|mjs|js)$/
  const SKIP = /^(private\/|node_modules\/|\.git\/|\.jj\/|\.true-up\/)|^\.true-up\.json$|^true-up\.config\.json$|depgraph\.(json|seed\.json)$/
  const changed = gitChanged(since).filter((f) => KEEP.test(f) && !SKIP.test(f))
  // a changed file is a legitimate SEED only if something declares a dependency on it (it's a source) or it's a steward
  const changedSources = changed.filter((f) => sources.has(f) || FACTS[f])
  const { seeds } = seedsForChange(since, changedSources, g)
  for (const f of changedSources) if (g.nodes['file:' + f]) seeds.add('file:' + f)
  const explained = new Set(changedSources)
  for (const h of dependentsOf(g, seeds)) { const s = srcFile(h.node); if (s) explained.add(s) }
  const violations = changed.filter((f) => !explained.has(f))
  if (JSONOUT) { jout({ ok: violations.length === 0, since, changed, explained: [...explained], violations }); process.exit(violations.length ? 1 : 0) }
  if (violations.length) {
    console.error(`out-of-scope edit(s) since ${since} — changed but NOT explained by the dependency graph:`)
    for (const f of violations) console.error(`  ${f}  (no declared dependency links it to what changed — anchor it, or this is scope creep / code-golf)`)
    console.error('Maintenance stays inside the deterministic blast radius; undeclared staleness is the audit\'s job.')
    process.exit(1)
  }
  console.log(`scope OK: all ${changed.length} changed file(s) since ${since} are explained by the graph (no code-golf).`)
  process.exit(0)
}

if (argv[0] === 'run' || argv[0] === 'true-up') {
  // Deterministic truing-up loop. The slow LLM prose-rewrite stays OUT (that's the agentic
  // /workflow layer). Repo-agnostic: change set from git; generators derived from the graph's
  // edges (`via`), never a hardcoded list — so this runs in any repo with the marker/seed convention.
  let since = flagVal('--since')
  if (since) { if (!refExists(since)) { console.error(`bad git ref: ${since}`); process.exit(2) } }
  else { since = refExists('HEAD~1') ? 'HEAD~1' : 'HEAD' } // shallow/initial repo: degrade to HEAD
  const strict = argv.includes('--strict')
  let graph
  try { graph = JSON.parse(readFileSync(OUT, 'utf8')) } catch { console.error(`build the graph first: ${rebuildHint}`); process.exit(2) }
  const changed = gitChanged(since)
  const { seeds, changedFacts } = seedsForChange(since, changed, graph)
  const hits = dependentsOf(graph, seeds)
  const mech = hits.filter((h) => h.propagation === 'mechanical')
  const adv = hits.filter((h) => h.propagation === 'advisory')
  console.log(`true-up since ${since}: ${changed.length} changed path(s), ${changedFacts.length} changed fact(s) → ${mech.length} mechanical / ${adv.length} advisory dependents`)
  // 1. REGENERATE mechanical dependents — run the generators the edges name (data-driven)
  const gens = [...new Set(mech.map((h) => h.via).filter(Boolean))]
  let regenFail = 0
  for (const gen of gens) {
    try { execFileSync('node', [resolve(ROOT, gen)], { stdio: 'ignore', cwd: ROOT, env: { ...process.env, TRUE_UP_REPO: ROOT } }); console.log(`  ✓ regenerated via ${gen}`) }
    catch { console.error(`  ✗ regenerate FAILED: ${gen}`); regenFail++ }
  }
  try { execFileSync('node', [self], { stdio: 'ignore', env: { ...process.env, TRUE_UP_REPO: ROOT } }) } catch {} // refresh the graph itself
  // 2. ADVISORY worklist — prose a human/LLM must rewrite; this CLI never edits prose
  if (adv.length) {
    console.log(`\n  ADVISORY — ${adv.length} doc(s) need review (← which fact moved):`)
    for (const h of adv) console.log(`    ${h.node.replace('file:', '')}  ←  ${h.fromSource.replace('fact:', '')}`)
  } else { console.log('  advisory: none') }
  // 3. VERIFY — repo-agnostic gate: policy clean (read exit code) + on-disk graph self-consistent
  let policyClean = true
  try { execFileSync('node', [self, '--policy'], { stdio: 'ignore', env: { ...process.env, TRUE_UP_REPO: ROOT } }) } catch { policyClean = false }
  let chk = false
  try { execFileSync('node', [self, '--check'], { stdio: 'ignore', env: { ...process.env, TRUE_UP_REPO: ROOT } }); chk = true } catch {}
  const green = regenFail === 0 && policyClean && chk
  console.log(`\n  verify: regen ${regenFail === 0 ? 'ok' : 'FAILED'} · policy ${policyClean ? 'clean' : 'VIOLATIONS'} · depgraph ${chk ? 'in-sync' : 'STALE'} → ${green ? 'GREEN ✓' : 'NOT GREEN ✗'}`)
  if (green && adv.length) console.log('  (mechanical trued up; advisory prose review still pending — that is the /workflow layer)')
  if (!green) process.exit(1)
  if (strict && adv.length) process.exit(2)
  process.exit(0)
}

// Anything past here is build (no args) or --check. Reject unknown commands instead of
// silently building + writing into the target repo (HIGH-4 foot-gun).
if (argv[0] && argv[0] !== '--check') {
  const guess = didYouMean(argv[0])
  console.error(`unknown command: ${argv[0]}${guess ? `\ndid you mean: ${guess} ?` : ''}\nrun: ${rebuildHint} --help   (or ${rebuildHint} capabilities for the full machine-readable contract)`)
  process.exit(2)
}

const graph = build()
// FAIL LOUD on unresolved anchors (build and --check)
if (graph.anchorErrors.length) {
  console.error('ANCHOR ERROR — these <!-- fact: … --> anchors do not resolve to a known fact node:')
  for (const e of graph.anchorErrors) console.error(`  ${e.file}: ${e.anchor}`)
  console.error('Fix the anchor path (or add the fact) and rerun. (stable-ID discipline: a wrong anchor must not pass silently.)')
  process.exit(1)
}

if (argv[0] === '--check') {
  const fresh = serialize(graph)
  const relOut = rel(OUT)
  if (argv.includes('--committed')) {
    // The drift gate: does the COMMITTED (or staged) graph blob match a fresh rebuild?
    // Catches "committed a source change without re-staging the regenerated graph", and an
    // untracked graph (false assurance). Prefers the staged blob (pre-commit), else HEAD (CI).
    const blob = (sp) => { try { return execFileSync('git', ['-C', ROOT, 'show', sp], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }) } catch { return null } }
    const committed = blob(':' + relOut) ?? blob('HEAD:' + relOut) // string | null (blob never returns undefined)
    const upToDate = committed !== null && committed === fresh
    const reason = committed === null ? 'not committed/staged' : (upToDate ? 'in sync' : 'stale vs fresh rebuild')
    if (JSONOUT) { jout({ mode: 'committed', path: relOut, upToDate, reason }); process.exit(upToDate ? 0 : 1) }
    if (committed === null) { console.error(`${relOut} is not committed/staged — build it and commit it (git is the database).`); process.exit(1) }
    if (!upToDate) { console.error(`${relOut} (committed) is STALE vs a fresh rebuild. Regenerate and stage: ${rebuildHint}`); process.exit(1) }
    console.log(`${relOut} (committed) is up to date ✓`)
    process.exit(0)
  }
  // default: working-tree freshness — is the on-disk graph what a fresh build produces?
  let cur = ''
  try { cur = readFileSync(OUT, 'utf8') } catch {}
  const upToDate = cur === fresh
  if (JSONOUT) { jout({ mode: 'worktree', path: relOut, upToDate, reason: upToDate ? 'in sync' : 'stale on disk' }); process.exit(upToDate ? 0 : 1) }
  if (!upToDate) { console.error(`${relOut} is STALE (on disk). Regenerate: ${rebuildHint}`); process.exit(1) }
  console.log(`${relOut} is up to date ✓`)
  process.exit(0)
}

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, serialize(graph))
const nNodes = Object.keys(graph.nodes).length
const nFacts = Object.keys(graph.nodes).filter((k) => k.startsWith('fact:')).length
const byBasis = graph.edges.reduce((a, e) => ((a[e.directionBasis] = (a[e.directionBasis] || 0) + 1), a), {})
const inert = !graph.edges.length || !Object.keys(FACTS).length
if (JSONOUT) jout({ out: rel(OUT), nodes: nNodes, factNodes: nFacts, edges: graph.edges.length, byDirectionBasis: byBasis, inert })
else {
  console.log(`${rel(OUT)} written: ${nNodes} nodes (${nFacts} fact-nodes), ${graph.edges.length} edges`)
  console.log(`  edges by direction-basis: ${JSON.stringify(byBasis)}`)
  // Empty-graph notice: distinguish "nothing changed" from "you declared nothing to track" (report LIMITATION).
  if (inert) console.error(`\nNOTICE: no ${!Object.keys(FACTS).length ? 'steward facts' : 'edges'} declared — the drift-detection layer is INERT (it passes --check trivially). Declare facts/seed in .true-up.json (see docs/CONFIG.md). Scope: only JSON files with top-level arrays-of-objects can be stewards; code files (e.g. .py) are valid seed-edge endpoints but are not auto-decomposed into facts.`)
}
